// <auto-generated/>
// analyzer-option: dotnet_code_quality.SK7081.threshold = 1
// Generated code is excluded: what a generator wires together is not a design decision anybody made.
namespace Fixtures;

class Alpha { }

class Beta { }

class Gamma { }

class GeneratedHub {
    Alpha? alpha;

    Beta? beta;

    Gamma? gamma;
}
