// <auto-generated/>
// analyzer-option: dotnet_code_quality.SK7080.threshold = 1
// Generated code is excluded: a generator's hierarchy is not a design decision anybody made.
namespace Fixtures;

class GeneratedBase { }

class GeneratedMiddle : GeneratedBase { }

class GeneratedLeaf : GeneratedMiddle { }
