// <auto-generated/>
// A generator emits what its input held; the byte is not a decision anybody made here.
// contains: U+200B
namespace Fixtures;

sealed class GeneratedKeys {
    public const string Tenant = "tenant​id";
}
