// <auto-generated/>
// A generator emits whatever key its schema names; the struct is not a decision made here.
using System.Collections.Generic;

namespace Fixtures {
    struct GeneratedKey {
        public int Value;
    }

    sealed class GeneratedTable {
        readonly Dictionary<GeneratedKey, string> rows = new Dictionary<GeneratedKey, string>();

        public int Size => rows.Count;
    }
}
