// <auto-generated/>
// A generator emits the assignment its template holds; it is not a decision made here.
namespace Fixtures {
    sealed class GeneratedRenderer {
        public void Render(string path) {
            path = "default.txt";
            System.Console.WriteLine(path);
        }
    }
}
