using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Rules.Async;
using Rikarin.Skala.Rules.Metadata;
using System.Collections.Immutable;
using System.Globalization;

namespace Rikarin.Skala.Rules.Tests;

/// <summary>
///     The two rules about the shape of an <c>async</c> method rather than what it does.
/// </summary>
/// <remarks>
///     ⚠ <c>SK3007</c> is in the analyzer list on purpose. <c>SK3031</c>'s fix elides an <c>await</c>,
///     which is exactly the bug <c>SK3007</c> reports when it happens inside a <c>using</c> — so "the
///     rule stays quiet where its own fix would create an <c>SK3007</c>" is a property of the pair and
///     asserting it needs both running at once.
/// </remarks>
public sealed class AsyncShapeBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new AsyncIteratorNotEnumeratedAnalyzer(), new TaskReturnedFromUsingAnalyzer(),
    ];

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All().Where(static f => f.RuleId is "SK3030")) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixtures_HaveExactCountsAndCarryTheirFix(RuleFixture fixture) {
        var findings = Analyze(RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path))
            .Where(diagnostic => diagnostic.Id == fixture.RuleId)
            .ToArray();

        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);

        var fixable = RuleCatalog.Get(fixture.RuleId).HasFix;
        Assert.All(findings, d => Assert.Equal(fixable, d.Properties.ContainsKey(FixEdits.CountKey)));
    }

    /// <summary>⚠ The whole statement becomes the loop, and the closing brace lands on the indent.</summary>
    [Fact]
    public void TheIteratorFix_WrapsTheCallInAnAwaitForeach() {
        var source = File.ReadAllText(
            Path.Combine(RuleFixtures.Root, "SK3030", "positive", "an-invocation-as-a-statement.cs")
        );

        Assert.Contains(
            "        await foreach (var _ in ProcessAsync()) {\n        }\n",
            Apply(source, "SK3030"),
            StringComparison.Ordinal
        );
    }

    /// <summary>
    ///     ⚠ The two guards that keep the fix compiling, each pinned by the fixture that breaks it.
    /// </summary>
    /// <remarks>
    ///     A synchronous enclosing body makes the inserted <c>await</c> CS4033, and a local already
    ///     named <c>_</c> makes the loop variable CS0136. Both are shapes where the bug is real and the
    ///     report is withheld, which is doc 08's rule about a finding an agent cannot act on.
    /// </remarks>
    [Theory]
    [InlineData("a-synchronous-method")]
    [InlineData("an-underscore-is-already-in-scope")]
    [InlineData("inside-a-lock")]
    public void WhereTheRewriteWouldNotCompile_NothingIsReported(string name) {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, "SK3030", "negative", name + ".cs"));

        Assert.DoesNotContain(Analyze(RuleFixtures.Compile(source, name + ".cs")), static d => d.Id == "SK3030");
    }

    [Fact]
    public void GeneratedCode_IsIgnored() {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(
                Path.Combine(RuleFixtures.Root, "SK3030", "positive", "an-invocation-as-a-statement.cs")
            );

        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) =>
        RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);

    static string Apply(string source, string id) {
        var diagnostic = Assert.Single(Analyze(RuleFixtures.Compile(source, "probe.cs")).Where(d => d.Id == id));

        var count = int.Parse(diagnostic.Properties[FixEdits.CountKey]!, CultureInfo.InvariantCulture);
        var edits = Enumerable.Range(0, count)
            .Select(index => new TextChange(
                    new TextSpan(
                        int.Parse(diagnostic.Properties[FixEdits.StartKey(index)]!, CultureInfo.InvariantCulture),
                        int.Parse(diagnostic.Properties[FixEdits.LengthKey(index)]!, CultureInfo.InvariantCulture)
                    ),
                    diagnostic.Properties[FixEdits.TextKey(index)]!
                )
            );

        return SourceText.From(source).WithChanges(edits).ToString();
    }
}
