using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Rules.Metadata;
using Rikarin.Skala.Rules.Performance;
using System.Collections.Immutable;
using System.Globalization;
using System.Runtime.Loader;

namespace Rikarin.Skala.Rules.Tests;

/// <summary>
///     The five rules whose whole decision is one declaration and what its body touches.
/// </summary>
public sealed class DeclarationPerformanceBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new NoncapturingLambdaAnalyzer(), new StatelessPrivateMethodAnalyzer(), new ImmutableStructAnalyzer(),
        new RedundantCapacityArgumentAnalyzer(), new ForcedGarbageCollectionAnalyzer(), new LoopClosureAnalyzer()
    ];

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All()
                         .Where(static fixture => fixture.RuleId is "SK4020"
                                 or "SK4021"
                                 or "SK4022"
                                 or "SK4023"
                                 or "SK4024"
                         )) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixtures_HaveExactCountsAndExpectedFixes(RuleFixture fixture) {
        var compilation = RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path);
        var findings = Analyze(compilation).Where(diagnostic => diagnostic.Id == fixture.RuleId).ToArray();
        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);
        Assert.All(
            findings,
            diagnostic => Assert.Equal(
                RuleCatalog.Get(fixture.RuleId).HasFix,
                diagnostic.Properties.ContainsKey(FixEdits.CountKey)
            )
        );
    }

    [Theory]
    [InlineData("SK4020", "lambda", LanguageVersion.CSharp8, LanguageVersion.CSharp9)]
    [InlineData("SK4022", "fields", LanguageVersion.CSharp7_1, LanguageVersion.CSharp7_2)]
    public void LanguageFloors_AreHonored(string id, string name, LanguageVersion before, LanguageVersion supported) {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.DoesNotContain(
            RuleFixtures.Analyze(Compile(source, before), Analyzers, TestContext.Current.CancellationToken),
            diagnostic => diagnostic.Id == id
        );
        Assert.Single(Analyze(Compile(source, supported)), diagnostic => diagnostic.Id == id);
    }

    [Theory]
    [InlineData("SK4020", "lambda")]
    [InlineData("SK4021", "expression_body")]
    [InlineData("SK4022", "fields")]
    [InlineData("SK4023", "list")]
    [InlineData("SK4024", "statement")]
    public void GeneratedCode_IsIgnored(string id, string name) {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    /// <summary>
    ///     ⚠ <c>SK4002</c> and <c>SK4020</c> are complements, and this is the assertion that says so.
    /// </summary>
    /// <remarks>
    ///     One reports a delegate capturing iteration-local storage and the other reports a declaration
    ///     capturing nothing at all. Two rules over the same syntax that both fire on one lambda is a
    ///     duplicate finding in every report and two baseline entries for one decision.
    /// </remarks>
    [Fact]
    public void TheNoncapturingRuleAndTheLoopClosureRule_NeverBothFire() {
        foreach (var fixture in RuleFixtures.All().Where(static fixture => fixture.RuleId is "SK4020" or "SK4002")) {
            var produced = Analyze(RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path));
            var closures = produced.Where(static diagnostic => diagnostic.Id == "SK4002").Select(Where).ToArray();
            var noncapturing = produced.Where(static diagnostic => diagnostic.Id == "SK4020").Select(Where).ToArray();
            Assert.Empty(closures.Intersect(noncapturing, StringComparer.Ordinal));
        }

        var loop = RuleFixtures.Compile(
            File.ReadAllText(Path.Combine(RuleFixtures.Root, "SK4020", "negative", "foreach_variable.cs")),
            "test.cs"
        );
        Assert.Single(Analyze(loop), static diagnostic => diagnostic.Id == "SK4002");
    }

    /// <summary>
    ///     ⚠ Transitive capture. A lambda that touches no outer name itself but calls a local function
    ///     that does is capturing, and the walk has to see through the call.
    /// </summary>
    [Fact]
    public void CaptureThroughANestedLocalFunction_IsStillACapture() {
        const string source = """
                              using System;

                              static class Indirect {
                                  public static Func<int> Build(int seed) =>
                                      () => {
                                          int Read() => seed;

                                          return Read();
                                      };
                              }
                              """;
        Assert.DoesNotContain(
            Analyze(RuleFixtures.Compile(source, "test.cs")),
            static diagnostic => diagnostic.Id == "SK4020"
        );
    }

    /// <summary>
    ///     <c>nameof</c> is decided at compile time, so a <c>static</c> lambda may name an instance field.
    /// </summary>
    [Fact]
    public void NameOfAnInstanceMember_DoesNotCapture() {
        const string source = """
                              using System;

                              sealed class Named {
                                  readonly int count = 1;

                                  public int Count => count;

                                  public Func<string> Describe() => () => nameof(count);
                              }
                              """;
        Assert.Single(Analyze(RuleFixtures.Compile(source, "test.cs")), static d => d.Id == "SK4020");
    }

    /// <summary>
    ///     ⚠ <c>SK4021</c>'s call-site check reads one file, so a type spread over two is declined.
    /// </summary>
    [Fact]
    public void APrivateMethodInAPartialType_IsNotReported() {
        var compilation = RuleFixtures.Compile(
            "partial class Owner { public int Use(int value) => Twice(value); }",
            "first.cs"
        );
        Assert.DoesNotContain(
            Analyze(AddFile(compilation, "partial class Owner { int Twice(int value) => value * 2; }", "second.cs")),
            static diagnostic => diagnostic.Id == "SK4021"
        );
    }

    /// <summary>A <c>GC</c> of somebody's own is not <c>System.GC</c>, in this file or another.</summary>
    [Fact]
    public void ASourceDeclaredGarbageCollector_IsNotTheFrameworkOne() {
        var compilation = RuleFixtures.Compile("static class Caller { public static void Purge() => GC.Collect(); }",
            "first.cs"
        );
        Assert.DoesNotContain(
            Analyze(AddFile(compilation, "static class GC { public static void Collect() { } }", "second.cs")),
            static diagnostic => diagnostic.Id == "SK4024"
        );
        Assert.Single(
            Analyze(
                RuleFixtures.Compile("static class Caller { public static void Purge() => System.GC.Collect(); }",
                    "test.cs"
                )
            ),
            static diagnostic => diagnostic.Id == "SK4024"
        );
    }

    [Fact]
    public void TheStaticLambdaFix_PreservesTheResult() =>
        AssertFixEquivalent(
            """
            using System;

            public class Probe {
                public static int Run() {
                    Func<int, int> twice = value => value * 2;
                    return twice(21);
                }
            }
            """,
            "SK4020",
            42
        );

    [Fact]
    public void TheStaticMethodFix_PreservesTheResult() =>
        AssertFixEquivalent(
            """
            public class Probe {
                public static int Run() => new Probe().Use(21);

                public int Use(int value) => Twice(value);

                int Twice(int value) => value * 2;
            }
            """,
            "SK4021",
            42
        );

    [Fact]
    public void TheReadonlyStructFix_PreservesTheResult() =>
        AssertFixEquivalent(
            """
            public struct Point {
                public readonly int X;

                public Point(int x) => X = x;

                public int Doubled => X * 2;
            }

            public class Probe {
                public static int Run() => new Point(21).Doubled;
            }
            """,
            "SK4022",
            42
        );

    [Fact]
    public void TheCapacityFix_PreservesTheResult() =>
        AssertFixEquivalent(
            """
            using System.Collections.Generic;

            public class Probe {
                public static int Run() {
                    var values = new List<int>(0);
                    values.Add(42);
                    return values[0] + values.Capacity - values.Capacity;
                }
            }
            """,
            "SK4023",
            42
        );

    static string Where(Diagnostic diagnostic) => diagnostic.Location.GetLineSpan().ToString();

    static CSharpCompilation Compile(string source, LanguageVersion version) {
        var compilation = RuleFixtures.Compile(source, "test.cs", version);
        return version < LanguageVersion.CSharp8
            ? compilation.WithOptions(compilation.Options.WithNullableContextOptions(NullableContextOptions.Disable))
            : compilation;
    }

    static void AssertFixEquivalent(string source, string id, int expected) {
        var before = RuleFixtures.Compile(source, "test.cs");
        var finding = Assert.Single(Analyze(before), diagnostic => diagnostic.Id == id);
        var edits = Enumerable.Range(0, int.Parse(finding.Properties[FixEdits.CountKey]!, CultureInfo.InvariantCulture))
            .Select(index => new TextChange(
                    new TextSpan(
                        int.Parse(finding.Properties[FixEdits.StartKey(index)]!, CultureInfo.InvariantCulture),
                        int.Parse(finding.Properties[FixEdits.LengthKey(index)]!, CultureInfo.InvariantCulture)
                    ),
                    finding.Properties[FixEdits.TextKey(index)]!
                )
            );
        var after = RuleFixtures.Compile(SourceText.From(source).WithChanges(edits).ToString(), "test.cs");
        Assert.DoesNotContain(Analyze(after), diagnostic => diagnostic.Id == id);
        Assert.Equal(expected, Run(before));
        Assert.Equal(expected, Run(after));
    }

    static CSharpCompilation AddFile(CSharpCompilation compilation, string source, string path) =>
        compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText(
                source,
                (CSharpParseOptions)compilation.SyntaxTrees.First().Options,
                path,
                cancellationToken: TestContext.Current.CancellationToken
            )
        );

    static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) {
        Assert.DoesNotContain(
            compilation.GetDiagnostics(TestContext.Current.CancellationToken),
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error
        );
        var diagnostics = RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);
        Assert.DoesNotContain(diagnostics, static diagnostic => diagnostic.Id == "AD0001");
        return diagnostics;
    }

    static int Run(CSharpCompilation compilation) {
        using var image = new MemoryStream();
        var emitted = compilation.Emit(image, cancellationToken: TestContext.Current.CancellationToken);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
        image.Position = 0;
        var context = new AssemblyLoadContext(Guid.NewGuid().ToString(), true);
        try {
            return Assert.IsType<int>(
                context.LoadFromStream(image).GetType("Probe")!.GetMethod("Run")!.Invoke(null, null)
            );
        } finally {
            context.Unload();
        }
    }
}
