using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Rules.Async;
using System.Collections.Immutable;
using System.Globalization;

namespace Rikarin.Skala.Rules.Tests;

/// <summary>
///     The three rules that ask what a <c>using</c> owns, and the two independents beside them.
/// </summary>
/// <remarks>
///     ⚠ <c>SK3007</c> is in the analyzer list on purpose. It is the <c>Task</c> shape of
///     <c>SK3512</c>, and the fact that exactly one of the two speaks on a given <c>return</c> is a
///     property of the pair rather than of either rule — asserting it needs both running at once.
/// </remarks>
public sealed class DisposalOwnershipBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new RedundantDisposeAnalyzer(), new TaskReturnedFromUsingAnalyzer()
    ];

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All().Where(static f => f.RuleId is "SK3510")) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixtures_HaveExactCountsAndCarryTheirFix(RuleFixture fixture) {
        var findings = Analyze(RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path))
            .Where(diagnostic => diagnostic.Id == fixture.RuleId)
            .ToArray();

        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);
        Assert.All(findings, static d => Assert.True(d.Properties.ContainsKey(FixEdits.CountKey)));
    }

    /// <summary>
    ///     ⚠ The whole line, and only that line.
    /// </summary>
    /// <remarks>
    ///     The interesting failure is not a fix that does not compile — <c>RuleFixtureTests</c> covers
    ///     that — but one that leaves an orphaned indent behind, or swallows the comment written above
    ///     the statement. Both parse, both re-bind, and both are wrong; only comparing the text catches
    ///     them.
    /// </remarks>
    [Fact]
    public void RedundantDisposeFix_TakesTheLineAndLeavesTheCommentAboveIt() {
        const string source = """
                              using System;
                              public sealed class Handle : IDisposable {
                                  public void Dispose() { }
                              }
                              public sealed class Consumer {
                                  public void Report() {
                                      using var handle = new Handle();
                                      // Belt and braces.
                                      handle.Dispose();
                                  }
                              }
                              """;

        const string expected = """
                                using System;
                                public sealed class Handle : IDisposable {
                                    public void Dispose() { }
                                }
                                public sealed class Consumer {
                                    public void Report() {
                                        using var handle = new Handle();
                                        // Belt and braces.
                                    }
                                }
                                """;

        Assert.Equal(expected, Apply(source, "SK3510"));
    }

    [Fact]
    public void ATrailingCommentSurvivesTheDeletion() {
        const string source = """
                              using System;
                              public sealed class Handle : IDisposable {
                                  public void Dispose() { }
                              }
                              public sealed class Consumer {
                                  public void Report() {
                                      using var handle = new Handle();
                                      handle.Dispose(); // Explain why.
                                  }
                              }
                              """;

        Assert.Contains("// Explain why.", Apply(source, "SK3510"), StringComparison.Ordinal);
    }

    [Fact]
    public void GeneratedCode_IsIgnored() {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(Path.Combine(RuleFixtures.Root, "SK3510", "positive", "a-using-declaration.cs"));
        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    internal static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) =>
        RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);

    /// <summary>Applies every edit one finding of <paramref name="id" /> carries.</summary>
    internal static string Apply(string source, string id) {
        var diagnostic = Assert.Single(Analyze(RuleFixtures.Compile(source, "probe.cs")).Where(d => d.Id == id));

        var count = int.Parse(diagnostic.Properties[FixEdits.CountKey]!, CultureInfo.InvariantCulture);
        var edits = Enumerable.Range(0, count)
            .Select(index => new TextChange(
                    new TextSpan(
                        int.Parse(diagnostic.Properties[FixEdits.StartKey(index)]!, CultureInfo.InvariantCulture),
                        int.Parse(diagnostic.Properties[FixEdits.LengthKey(index)]!, CultureInfo.InvariantCulture)
                    ),
                    diagnostic.Properties[FixEdits.TextKey(index)]!
                )
            );

        return SourceText.From(source).WithChanges(edits).ToString();
    }
}
