using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Rules.Correctness;
using Rikarin.Skala.Rules.Maintainability;
using Rikarin.Skala.Rules.Modernization;
using Rikarin.Skala.Rules.Performance;
using System.Collections.Immutable;
using System.Globalization;
using System.Runtime.Loader;

namespace Rikarin.Skala.Rules.Tests;

public sealed class LockAndValueBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new DedicatedLockAnalyzer(), new FloatingPointEqualityAnalyzer(),
        new ConstrainedBoxingAnalyzer(), new LargeStructArgumentAnalyzer(), new CommentedCodeAnalyzer()
    ];

    const string Large = "struct Large { public long A, B, C, D, E, F, G, H, I; } ";

    const string Copy =
        "class C { void Use(Large value) { } void M(Large value) { for (int i = 0; i < 10; i++) Use(value); } }";

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All()
                         .Where(static f => f.RuleId is "SK1023" or "SK2003" or "SK4004" or "SK4007" or "SK7060")) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixtures_HaveExactCountsAndExpectedFixes(RuleFixture fixture) {
        var compilation = RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path);
        var findings = Analyze(compilation).Where(diagnostic => diagnostic.Id == fixture.RuleId).ToArray();
        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);
        Assert.All(
            findings,
            diagnostic => Assert.Equal(fixture.RuleId == "SK1023", diagnostic.Properties.ContainsKey(FixEdits.CountKey))
        );
    }

    [Fact]
    public void LockFix_RequiresCSharp13() {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, "SK1023", "positive", "instance.cs"));
        Assert.DoesNotContain(
            Analyze(RuleFixtures.Compile(source, "test.cs", LanguageVersion.CSharp12)),
            static d => d.Id == "SK1023"
        );
        Assert.Single(
            Analyze(RuleFixtures.Compile(source, "test.cs", LanguageVersion.CSharp13)),
            static d => d.Id == "SK1023"
        );
    }

    [Fact]
    public void LockFix_PreservesMutualExclusionAndReentrancy() {
        const string source = """
                              using System.Threading.Tasks;
                              public class Probe {
                                  readonly object gate = new();
                                  int count;
                                  void Increment() { lock (gate) { lock (gate) { count++; } } }
                                  public static int Run() {
                                      var probe = new Probe();
                                      Parallel.For(0, 1000, _ => probe.Increment());
                                      return probe.count;
                                  }
                              }
                              """;
        var before = RuleFixtures.Compile(source, "probe.cs");
        var diagnostic = Assert.Single(Analyze(before), static d => d.Id == "SK1023");
        var edits = Enumerable.Range(
            0,
            int.Parse(diagnostic.Properties[FixEdits.CountKey]!, CultureInfo.InvariantCulture)
        )
            .Select(index => new TextChange(
                    new TextSpan(
                        int.Parse(diagnostic.Properties[FixEdits.StartKey(index)]!, CultureInfo.InvariantCulture),
                        int.Parse(diagnostic.Properties[FixEdits.LengthKey(index)]!, CultureInfo.InvariantCulture)
                    ),
                    diagnostic.Properties[FixEdits.TextKey(index)]!
                )
            );
        var after = RuleFixtures.Compile(SourceText.From(source).WithChanges(edits).ToString(), "probe.cs");
        Assert.DoesNotContain(Analyze(after), static d => d.Id == "SK1023");
        Assert.Equal(1000, Run(before));
        Assert.Equal(1000, Run(after));
    }

    [Theory]
    [InlineData("SK1023", "instance")]
    [InlineData("SK2003", "double")]
    [InlineData("SK4004", "comparable")]
    [InlineData("SK4007", "for")]
    [InlineData("SK7060", "line-comments")]
    public void GeneratedCode_IsIgnored(string id, string name) {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    [Theory]
    [InlineData("64", true)]
    [InlineData("71", true)]
    [InlineData("72", false)]
    [InlineData("128", false)]
    [InlineData("0", true)]
    [InlineData("-1", true)]
    [InlineData("bad", true)]
    [InlineData("2147483648", true)]
    public void SizeThreshold_IsStrictAndInvalidValuesFallBack(string threshold, bool reports) {
        var source = "// analyzer-option: dotnet_code_quality.SK4007.threshold = " + threshold + "\n" + Large + Copy;
        var findings = Analyze(RuleFixtures.Compile(source, "test.cs")).Where(static d => d.Id == "SK4007").ToArray();
        Assert.Equal(reports ? 1 : 0, findings.Length);
        Assert.All(findings, static d => Assert.Equal("72", d.Properties["skala.size.lower_bound"]));
    }

    [Theory]
    [InlineData("public long A, B, C, D, E, F, G, H, I;", 72)]
    [InlineData("public byte A; public long B, C, D, E, F, G, H, I;", 65)]
    [InlineData("public decimal A, B, C, D, E;", 80)]
    public void PayloadBound_DoesNotExceedRuntimeSize(string fields, int expectedBound) {
        var source = "struct Large { "
            + fields
            + " } "
            + Copy
            + " public static class Probe { public static int Run() => System.Runtime.CompilerServices.Unsafe.SizeOf<Large>(); }";
        var compilation = RuleFixtures.Compile(source, "test.cs");
        var finding = Assert.Single(Analyze(compilation), static d => d.Id == "SK4007");
        Assert.Equal(
            expectedBound.ToString(CultureInfo.InvariantCulture),
            finding.Properties["skala.size.lower_bound"]
        );
        Assert.True(expectedBound <= Run(compilation));
    }

    [Fact]
    public void OtherFileLayout_IsNotAFileLocalFact() {
        var compilation = AddFile(RuleFixtures.Compile(Copy, "test.cs"), Large, "large.cs");
        Assert.DoesNotContain(Analyze(compilation), static d => d.Id == "SK4007");
    }

    [Fact]
    public void OtherFileLayoutConstants_AreNotFileLocalFacts() {
        var compilation = RuleFixtures.Compile(
            "[System.Runtime.InteropServices.StructLayout(Layout.Mode)] " + Large + Copy,
            "test.cs"
        );
        compilation = AddFile(
            compilation,
            "class Layout { public const System.Runtime.InteropServices.LayoutKind Mode = System.Runtime.InteropServices.LayoutKind.Sequential; }",
            "layout.cs"
        );
        Assert.DoesNotContain(Analyze(compilation), static d => d.Id == "SK4007");
    }

    [Fact]
    public void FileLocalSequentialLayout_IsSupported() {
        var compilation = RuleFixtures.Compile(
            "[System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential, Pack = 1)] "
            + Large
            + Copy,
            "test.cs"
        );
        Assert.Single(Analyze(compilation), static d => d.Id == "SK4007");
    }

    [Fact]
    public void OtherFileConstants_DoNotChangeCachedFloatingPointDecisions() {
        var compilation = RuleFixtures.Compile(
            "class C { bool M(double x, double y) => x + y == Limits.Expected; }",
            "test.cs"
        );
        compilation = AddFile(compilation, "class Limits { public const double Expected = 0.3; }", "limits.cs");
        Assert.DoesNotContain(Analyze(compilation), static d => d.Id == "SK2003");
    }

    [Theory]
    [InlineData(1, false)]
    [InlineData(2, true)]
    [InlineData(100, true)]
    [InlineData(101, false)]
    public void CommentGroups_AreBoundedAndRequireMultipleStatements(int lines, bool expected) {
        var source = "class C { void M() {\n" + string.Join("\n", Enumerable.Repeat("// Run();", lines)) + "\n} }";
        Assert.Equal(expected, Analyze(RuleFixtures.Compile(source, "test.cs")).Any(static d => d.Id == "SK7060"));
    }

    [Fact]
    public void CommentSizeAndNestingBudgets_AreConservative() {
        var large = "class C { void M() {\n// A(\"" + new string('x', 9000) + "\");\n// B();\n} }";
        Assert.DoesNotContain(Analyze(RuleFixtures.Compile(large, "test.cs")), static d => d.Id == "SK7060");
        var nested = "class C { void M() {\n/* "
            + new string('{', 140)
            + "A(); B();"
            + new string('}', 140)
            + " */\n} }";
        Assert.DoesNotContain(Analyze(RuleFixtures.Compile(nested, "test.cs")), static d => d.Id == "SK7060");
    }

    static CSharpCompilation AddFile(CSharpCompilation compilation, string source, string path) =>
        compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText(
                source,
                (CSharpParseOptions)compilation.SyntaxTrees.First().Options,
                path,
                cancellationToken: TestContext.Current.CancellationToken
            )
        );

    static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) {
        Assert.DoesNotContain(
            compilation.GetDiagnostics(TestContext.Current.CancellationToken),
            static d => d.Severity == DiagnosticSeverity.Error
        );
        var diagnostics = RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);
        Assert.DoesNotContain(diagnostics, static d => d.Id == "AD0001");
        return diagnostics;
    }

    static int Run(CSharpCompilation compilation) {
        using var image = new MemoryStream();
        var emitted = compilation.Emit(image, cancellationToken: TestContext.Current.CancellationToken);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
        image.Position = 0;
        var context = new AssemblyLoadContext(Guid.NewGuid().ToString(), true);
        try {
            return Assert.IsType<int>(
                context.LoadFromStream(image).GetType("Probe")!.GetMethod("Run")!.Invoke(null, null)
            );
        } finally {
            context.Unload();
        }
    }
}
