using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Rikarin.Skala.Rules.Async;
using Rikarin.Skala.Rules.Metadata;
using Rikarin.Skala.Rules.Performance;
using Rikarin.Skala.Rules.TestQuality;
using System.Collections.Immutable;

namespace Rikarin.Skala.Rules.Tests;

public sealed class PerformanceAndConcurrencyBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new SharedLazyAnalyzer(), new HotPathLinqAnalyzer(),
        new LoopClosureAnalyzer(), new ImmediateMaterializationAnalyzer(), new NondeterministicAssertionAnalyzer()
    ];

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All()
                         .Where(static f => f.RuleId is "SK3009" or "SK4001" or "SK4002" or "SK4006" or "SK8007")) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void EveryFixture_HasAnExactCountAndNoAutomaticFix(RuleFixture fixture) {
        var compilation = RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path);
        var findings = Analyze(compilation).Where(diagnostic => diagnostic.Id == fixture.RuleId).ToArray();
        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);
        Assert.All(findings, static finding => Assert.DoesNotContain(FixEdits.CountKey, finding.Properties.Keys));
        Assert.False(RuleCatalog.Get(fixture.RuleId).HasFix);
    }

    [Fact]
    public void HotPathPolicy_IsDisabledUntilExplicitlyEnabled() {
        var compilation = RuleFixtures.Compile(
            "using System.Linq; class C { int M(int[] x) => x.Count(); }",
            "test.cs"
        );
        var disabled = compilation.WithOptions(
            compilation.Options.WithSpecificDiagnosticOptions(ImmutableDictionary<string, ReportDiagnostic>.Empty)
        );
        Assert.DoesNotContain(Analyze(disabled), static finding => finding.Id == "SK4001");
        Assert.Single(Analyze(compilation), static finding => finding.Id == "SK4001");
    }

    [Theory]
    [InlineData("Limits.Safe")]
    [InlineData("Alias")]
    public void SharedLazy_DoesNotCacheOtherFilesConstantInitializers(string value) {
        var compilation = RuleFixtures.Compile(
            $"using System; class C {{ const bool Alias = Limits.Safe; static Lazy<int> Value = new(() => 1, {value}); }}",
            "test.cs"
        );
        compilation = compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText(
                "class Limits { public const bool Safe = false; }",
                (CSharpParseOptions)compilation.SyntaxTrees.First().Options,
                "limits.cs",
                cancellationToken: TestContext.Current.CancellationToken
            )
        );
        Assert.DoesNotContain(Analyze(compilation), static finding => finding.Id == "SK3009");
    }

    [Theory]
    [InlineData("SK3009", "boolean-false")]
    [InlineData("SK4001", "fluent-pipeline")]
    [InlineData("SK4002", "foreach")]
    [InlineData("SK4006", "array")]
    [InlineData("SK8007", "clock")]
    public void GeneratedCode_IsIgnored(string id, string name) {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    [Fact]
    public void PreCSharp5Foreach_DoesNotClaimFreshIterationStorage() {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, "SK4002", "positive", "foreach.cs"));
        var compilation = RuleFixtures.Compile(source, "test.cs", LanguageVersion.CSharp4);
        compilation = compilation.WithOptions(
            compilation.Options.WithNullableContextOptions(NullableContextOptions.Disable)
        );
        Assert.DoesNotContain(Analyze(compilation), static finding => finding.Id == "SK4002");
    }

    [Theory]
    [InlineData("System.DateTime.Now")]
    [InlineData("System.DateTime.UtcNow")]
    [InlineData("System.DateTime.Today")]
    [InlineData("System.DateTimeOffset.Now")]
    [InlineData("System.DateTimeOffset.UtcNow")]
    [InlineData("System.Guid.NewGuid()")]
    [InlineData("System.Random.Shared.Next()")]
    [InlineData("System.Random.Shared.NextInt64()")]
    [InlineData("System.Random.Shared.NextDouble()")]
    [InlineData("System.Random.Shared.NextSingle()")]
    [InlineData("new System.Random().Next()")]
    public void AssertionSources_AreBoundAndDeduplicatedPerAssertion(string expression) {
        var source = $"class C {{ [Xunit.Fact] public void M() {{ Xunit.Assert.Equal({expression}, {expression}); }} }}";
        Assert.Single(Analyze(RuleFixtures.Compile(source, "test.cs")), static finding => finding.Id == "SK8007");
    }

    [Fact]
    public void DerivedTestAttributes_AreRecognizedSemantically() {
        const string source =
            "class CustomFactAttribute : Xunit.FactAttribute { } class C { [CustomFact] public void M() { Xunit.Assert.NotEqual(System.Guid.Empty, System.Guid.NewGuid()); } }";
        Assert.Single(Analyze(RuleFixtures.Compile(source, "test.cs")), static finding => finding.Id == "SK8007");
    }

    [Fact]
    public void AliasedSourceReferenceInLoopBody_PreservesSnapshotWarningBoundary() {
        const string source =
            "using System.Linq; using System.Collections.Generic; class C { void M(List<int> values) { foreach (var x in values.ToList()) { var alias = values; alias.Remove(x); } } }";
        Assert.DoesNotContain(
            Analyze(RuleFixtures.Compile(source, "test.cs")),
            static finding => finding.Id == "SK4006"
        );
    }

    static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) {
        Assert.DoesNotContain(
            compilation.GetDiagnostics(TestContext.Current.CancellationToken),
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error
        );
        var diagnostics = RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);
        Assert.DoesNotContain(diagnostics, static diagnostic => diagnostic.Id == "AD0001");
        return diagnostics;
    }
}
