<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="fixtures/**/*.cs" />
    <None Include="fixtures/**/*.cs" />
    <Compile Remove="corpus/**/*.cs" />
    <None Include="corpus/**/*.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Rikarin.Skala.Rules/Rikarin.Skala.Rules.csproj" />
    <ProjectReference Include="../Rikarin.Skala.Rules.Metadata/Rikarin.Skala.Rules.Metadata.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>
</Project>
