using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Rules.Correctness;
using Rikarin.Skala.Rules.Modernization;
using Rikarin.Skala.Rules.Performance;
using System.Collections.Immutable;
using System.Globalization;
using System.Runtime.Loader;

namespace Rikarin.Skala.Rules.Tests;

public sealed class StorageAndSpanBatchTests {
    static readonly ImmutableArray<DiagnosticAnalyzer> Analyzers = [
        new FieldBackedPropertyAnalyzer(), new SearchValuesAnalyzer(), new FrozenDictionaryAnalyzer(),
        new ReadonlyStructMutationAnalyzer(), new ParamsSpanOverloadAnalyzer()
    ];

    public static TheoryData<RuleFixture> Fixtures {
        get {
            var data = new TheoryData<RuleFixture>();
            foreach (var fixture in RuleFixtures.All()
                         .Where(static fixture => fixture.RuleId is "SK1003"
                                 or "SK1022"
                                 or "SK1025"
                                 or "SK2005"
                                 or "SK4003"
                         )) {
                data.Add(fixture);
            }

            return data;
        }
    }

    [Theory]
    [MemberData(nameof(Fixtures))]
    public void Fixtures_HaveExactCountsAndExpectedFixes(RuleFixture fixture) {
        var compilation = RuleFixtures.Compile(File.ReadAllText(fixture.Path), fixture.Path);
        var findings = Analyze(compilation).Where(diagnostic => diagnostic.Id == fixture.RuleId).ToArray();
        Assert.Equal(fixture.ShouldFire ? 1 : 0, findings.Length);
        Assert.All(
            findings,
            diagnostic => Assert.Equal(
                fixture.RuleId is "SK1003" or "SK1022" or "SK1025",
                diagnostic.Properties.ContainsKey(FixEdits.CountKey)
            )
        );
    }

    [Theory]
    [InlineData("SK1003", "validation", LanguageVersion.CSharp13, LanguageVersion.CSharp14)]
    [InlineData("SK1022", "array", LanguageVersion.CSharp7_1, LanguageVersion.CSharp7_2)]
    [InlineData("SK4003", "explicit", LanguageVersion.CSharp11, LanguageVersion.CSharp12)]
    public void LanguageFloors_AreHonored(string id, string name, LanguageVersion before, LanguageVersion supported) {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.DoesNotContain(
            RuleFixtures.Analyze(
                RuleFixtures.Compile(source, "test.cs", before),
                Analyzers,
                TestContext.Current.CancellationToken
            ),
            diagnostic => diagnostic.Id == id
        );
        var compilation = RuleFixtures.Compile(source, "test.cs", supported);
        if (supported < LanguageVersion.CSharp8) {
            compilation = compilation.WithOptions(
                compilation.Options.WithNullableContextOptions(NullableContextOptions.Disable)
            );
        }

        Assert.Single(Analyze(compilation), diagnostic => diagnostic.Id == id);
    }

    [Theory]
    [InlineData("SK1003", "validation")]
    [InlineData("SK1022", "array")]
    [InlineData("SK1025", "strings")]
    [InlineData("SK2005", "increment")]
    [InlineData("SK4003", "explicit")]
    public void GeneratedCode_IsIgnored(string id, string name) {
        var source = "// <auto-generated/>\n"
            + File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        Assert.Empty(Analyze(RuleFixtures.Compile(source, "generated.cs")));
    }

    [Theory]
    [InlineData("SK1022", "array", "namespace System.Buffers { public class SearchValues<T> { } }")]
    [InlineData("SK1025", "strings", "namespace System.Collections.Frozen { public class FrozenDictionary<K,V> { } }")]
    [InlineData("SK4003", "explicit", "namespace System { public class ReadOnlySpan<T> { } }")]
    public void SourceApiLookalikes_AreNotFrameworkSupport(string id, string name, string lookalike) {
        var source = File.ReadAllText(Path.Combine(RuleFixtures.Root, id, "positive", name + ".cs"));
        var compilation = AddFile(RuleFixtures.Compile(source, "test.cs"), lookalike, "lookalike.cs");
        Assert.DoesNotContain(Analyze(compilation), diagnostic => diagnostic.Id == id);
    }

    [Fact]
    public void CrossFileConstantsAndBodies_AreNotFileLocalProofs() {
        var search =
            "using System; class C { static readonly char[] chars = new[] { Limits.First, 'b', 'c', 'd' }; int M(ReadOnlySpan<char> text) => text.IndexOfAny(chars); }";
        Assert.DoesNotContain(
            Analyze(
                AddFile(
                    RuleFixtures.Compile(search, "test.cs"),
                    "class Limits { public const char First = 'a'; }",
                    "limits.cs"
                )
            ),
            static diagnostic => diagnostic.Id == "SK1022"
        );
        var frozen =
            """using System.Collections.Generic; class C { static readonly Dictionary<string,int> map = new() { {"a", Limits.Value} }; int M(string key) => map[key]; }""";
        Assert.DoesNotContain(
            Analyze(
                AddFile(
                    RuleFixtures.Compile(frozen, "test.cs"),
                    "class Limits { public const int Value = 1; }",
                    "limits.cs"
                )
            ),
            static diagnostic => diagnostic.Id == "SK1025"
        );
        var mutation = "class C { readonly Counter counter; void M() => counter.Increment(); }";
        Assert.DoesNotContain(
            Analyze(
                AddFile(
                    RuleFixtures.Compile(mutation, "test.cs"),
                    "struct Counter { int value; public void Increment() => value++; }",
                    "counter.cs"
                )
            ),
            static diagnostic => diagnostic.Id == "SK2005"
        );
    }

    [Fact]
    public void FieldFix_PreservesValidationAndSetterEffects() {
        const string source = """
                              public class Probe {
                                  int count;
                                  public int Count { get => count; set => count = System.Math.Max(0, value); }
                                  public static int Run() {
                                      var probe = new Probe();
                                      probe.Count = -5;
                                      var zero = probe.Count;
                                      probe.Count = 7;
                                      return zero + probe.Count;
                                  }
                              }
                              """;
        AssertFixEquivalent(source, "SK1003", 7);
    }

    [Fact]
    public void SearchFix_PreservesAllFourSpanOperationsAndUnicode() {
        const string source = """
                              using System;
                              public class Probe {
                                  static readonly char[] chars = new[] { '\0', '\u00e9', '\u2603', 'x', 'y' };
                                  public static int Run() {
                                      ReadOnlySpan<char> text = "a\u2603x";
                                      return text.IndexOfAny(chars) + text.IndexOfAnyExcept(chars)
                                          + (text.ContainsAny(chars) ? 10 : 0) + (text.ContainsAnyExcept(chars) ? 100 : 0);
                                  }
                              }
                              """;
        AssertFixEquivalent(source, "SK1022", 111);
    }

    [Fact]
    public void FrozenFix_PreservesLookupAndMissingKeyBehavior() {
        const string source = """
                              using System;
                              using System.Collections.Generic;
                              public class Probe {
                                  static readonly Dictionary<string,int> map = new() { { "a", 1 }, { "b", 2 } };
                                  public static int Run() {
                                      map.TryGetValue("b", out var value);
                                      var result = map["a"] + value + map.Count + (map.ContainsKey("missing") ? 100 : 0);
                                      try { result += map["missing"]; } catch (KeyNotFoundException) { result += 10; }
                                      try { result += map[null!]; } catch (ArgumentNullException) { result += 100; }
                                      return result;
                                  }
                              }
                              """;
        AssertFixEquivalent(source, "SK1025", 115);
    }

    [Fact]
    public void FrozenFix_PreservesDuplicateKeyValidation() {
        const string source = """
                              using System;
                              using System.Collections.Generic;
                              class Table {
                                  static readonly Dictionary<string,int> map = new() { { "a", 1 }, { "a", 2 } };
                                  public static int Read() => map["a"];
                              }
                              public class Probe {
                                  public static int Run() {
                                      try { return Table.Read(); }
                                      catch (TypeInitializationException error) { return error.InnerException is ArgumentException ? 1 : 0; }
                                  }
                              }
                              """;
        AssertFixEquivalent(source, "SK1025", 1);
    }

    [Fact]
    public void ReadonlyMutation_IsDiscardedAtRuntime() {
        const string source = """
                              struct Counter { public int Value; public void Increment() => Value++; }
                              public class Probe {
                                  readonly Counter counter = new();
                                  public static int Run() {
                                      var probe = new Probe();
                                      probe.counter.Increment();
                                      return probe.counter.Value;
                                  }
                              }
                              """;
        var compilation = RuleFixtures.Compile(source, "test.cs");
        Assert.Single(Analyze(compilation), static diagnostic => diagnostic.Id == "SK2005");
        Assert.Equal(0, Run(compilation));
    }

    static void AssertFixEquivalent(string source, string id, int expected) {
        var before = RuleFixtures.Compile(source, "test.cs");
        var finding = Assert.Single(Analyze(before), diagnostic => diagnostic.Id == id);
        var edits = Enumerable.Range(0, int.Parse(finding.Properties[FixEdits.CountKey]!, CultureInfo.InvariantCulture))
            .Select(index => new TextChange(
                    new TextSpan(
                        int.Parse(finding.Properties[FixEdits.StartKey(index)]!, CultureInfo.InvariantCulture),
                        int.Parse(finding.Properties[FixEdits.LengthKey(index)]!, CultureInfo.InvariantCulture)
                    ),
                    finding.Properties[FixEdits.TextKey(index)]!
                )
            );
        var after = RuleFixtures.Compile(SourceText.From(source).WithChanges(edits).ToString(), "test.cs");
        Assert.DoesNotContain(Analyze(after), diagnostic => diagnostic.Id == id);
        Assert.Equal(expected, Run(before));
        Assert.Equal(expected, Run(after));
    }

    static CSharpCompilation AddFile(CSharpCompilation compilation, string source, string path) =>
        compilation.AddSyntaxTrees(
            CSharpSyntaxTree.ParseText(
                source,
                (CSharpParseOptions)compilation.SyntaxTrees.First().Options,
                path,
                cancellationToken: TestContext.Current.CancellationToken
            )
        );

    static ImmutableArray<Diagnostic> Analyze(CSharpCompilation compilation) {
        Assert.DoesNotContain(
            compilation.GetDiagnostics(TestContext.Current.CancellationToken),
            static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error
        );
        var diagnostics = RuleFixtures.Analyze(compilation, Analyzers, TestContext.Current.CancellationToken);
        Assert.DoesNotContain(diagnostics, static diagnostic => diagnostic.Id == "AD0001");
        return diagnostics;
    }

    static int Run(CSharpCompilation compilation) {
        using var image = new MemoryStream();
        var emitted = compilation.Emit(image, cancellationToken: TestContext.Current.CancellationToken);
        Assert.True(emitted.Success, string.Join("\n", emitted.Diagnostics));
        image.Position = 0;
        var context = new AssemblyLoadContext(Guid.NewGuid().ToString(), true);
        try {
            return Assert.IsType<int>(
                context.LoadFromStream(image).GetType("Probe")!.GetMethod("Run")!.Invoke(null, null)
            );
        } finally {
            context.Unload();
        }
    }
}
