// <auto-generated/>
// A generator emits the call shape its template holds; it is not a decision made here.
using System;
using System.Threading.Tasks;

public sealed class GeneratedWiring {
    public void Wire() {
        Action callback = async () => await Task.Yield();

        callback();
    }
}
