<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rikarin.Skala.Testing</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Formatting/Rikarin.Skala.Formatting.CSharp/Rikarin.Skala.Formatting.CSharp.csproj" />
    <ProjectReference Include="../../Analysis/Rikarin.Skala.Analysis/Rikarin.Skala.Analysis.csproj" />
    <ProjectReference Include="../../Tools/Rikarin.Skala.Cli/Rikarin.Skala.Cli.csproj"
                      ReferenceOutputAssembly="false"
                      Private="false"
                      SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyMetadata Include="SkalaRepositoryRoot" Value="$(SkalaRepositoryRoot)" />
    <AssemblyMetadata Include="SkalaCliAssembly"
                      Value="$(SkalaRepositoryRoot)Tools/Rikarin.Skala.Cli/bin/$(Configuration)/net10.0/skala.dll" />
  </ItemGroup>
</Project>
