using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Rikarin.Skala.Formatting.CSharp;

namespace Rikarin.Skala.Testing;

/// <summary>How a corpus file's formatting is destroyed before both tools are asked to repair it.</summary>
/// <remarks>
/// ⚠ Two modes rather than one, and the reason is a property of this configuration rather than
/// thoroughness. The export sets <c>resharper_keep_user_linebreaks = true</c> and
/// <c>keep_user_wrapping = true</c> — ADR-002's preserve-and-repair model — so
/// <b>destroying the author's line breaks destroys the input those options act on</b>. A
/// collapse-everything test measures the <em>reflow</em> path and says nothing about the
/// <em>preserve</em> path, which is the one that runs in production.
/// </remarks>
public enum UnformatMode {
    /// <summary>
    /// Plausible bad formatting: random indentation, line breaks moved to legal-but-wrong places,
    /// blank lines added and removed, inter-token spacing randomised.
    /// </summary>
    /// <remarks>
    /// ⚠ This is the mode that matters most. The author's breaks are <b>different</b>, not absent,
    /// so both tools still exercise <c>keep_existing_*</c> and the preserve machinery — and it is
    /// what real input looks like and what an AI writes.
    /// </remarks>
    Scramble,

    /// <summary>
    /// Minimal legal whitespace, everything joined onto as few lines as the language allows.
    /// </summary>
    /// <remarks>
    /// No line-break information survives, so both tools must build the layout from nothing. This is
    /// the hardest test of the fitting engine and the wrap options, and the one whose null
    /// hypothesis is near zero.
    /// </remarks>
    Collapse
}

/// <summary>One degraded file, and what it cost to make.</summary>
public sealed record DegradedSource(UnformatMode Mode, string Text, int Lines, bool Glued);

/// <summary>
/// Degrades a file's formatting without changing the program.
/// </summary>
/// <remarks>
/// ⚠ Both modes are <b>parse-preserving and token-preserving</b>, and neither re-derives what is
/// safe to touch: <see cref="FuzzMutations.SourceMap"/> already knows which bytes are data —
/// disabled <c>#if</c> text under <em>either</em> symbol set, verbatim and raw strings,
/// interpolation holes, <c>///</c> runs — and it cost that agent 3 500 false reports to get right.
/// This file consumes that map through its public surface and edits nothing in it.
/// <para>
/// ⚠ The duplication that remains is <see cref="Splice"/> and the sampling, which are private in
/// <c>FuzzMutations</c>. They are eight lines each and copying them was cheaper than widening a file
/// another agent is working in; the two copies want folding into one helper once both land.
/// </para>
/// <para>
/// ⚠ Everything here is verified rather than argued: <see cref="Degrade"/> returns <c>null</c> when
/// the degraded text's token stream is not identical to the original's <b>under both symbol
/// sets</b>, or when it introduces a parse error. A degradation that changes the program measures
/// the degrader rather than the formatter, and the fuzzer's history says that is the failure mode to
/// expect.
/// </para>
/// </remarks>
public static class Unformat {
    /// <summary>The two symbol sets every degradation is checked under.</summary>
    /// <remarks>
    /// ⚠ Empty and <see cref="Corpus.PropertySymbols"/>, for the reason
    /// <c>FuzzMutations.SourceMap.BuildOtherSet</c> records: which text is
    /// <see cref="SyntaxKind.DisabledTextTrivia"/> is entirely a function of the symbol set, so a
    /// check run under one set walks straight into the other's data.
    /// </remarks>
    public static IReadOnlyList<IReadOnlyList<string>> CheckedSymbolSets { get; } = [[], Corpus.PropertySymbols];

    public static string Name(UnformatMode mode) =>
        mode switch {
            UnformatMode.Scramble => "scramble",
            UnformatMode.Collapse => "collapse",
            _ => throw new ArgumentOutOfRangeException(nameof(mode))
        };

    public static IReadOnlyList<UnformatMode> Modes { get; } = [UnformatMode.Scramble, UnformatMode.Collapse];

    public static UnformatMode? Parse(string name) =>
        Modes.Cast<UnformatMode?>().FirstOrDefault(mode => Name(mode!.Value) == name);

    /// <summary>
    /// Degrades <paramref name="source"/>, or returns <c>null</c> when the result cannot be proved
    /// to be the same program.
    /// </summary>
    /// <param name="seed">
    /// ⚠ Derived from the file's path rather than drawn from a stream, exactly as
    /// <see cref="CorpusSample"/> draws its sample: a corpus whose content depends on enumeration
    /// order is a corpus that cannot be regenerated by the next person.
    /// </param>
    public static DegradedSource? Degrade(UnformatMode mode, string source, ulong seed) {
        var normalised = Normalise(source);
        var original = Fingerprints(normalised);
        if (original is null) {
            // A file that does not parse cleanly to begin with is one the formatter hands back
            // byte-identical by policy (ADR-003), so degrading it would measure nothing.
            return null;
        }

        var glued = false;
        string? degraded;
        switch (mode) {
            case UnformatMode.Collapse:
                degraded = Collapse(normalised, alwaysSpace: false);
                if (degraded is null || !Matches(degraded, original)) {
                    // ⚠ The fallback is not politeness. `NeedsSpace` decides token adjacency from a
                    // six-character window, which is conservative by construction but is still a
                    // guess; one space between every pair of tokens is legal everywhere and still
                    // destroys every line break, which is what this mode is for.
                    degraded = Collapse(normalised, alwaysSpace: true);
                    glued = true;
                }

                break;

            case UnformatMode.Scramble:
                degraded = Scramble(normalised, new FuzzRandom(seed));
                break;

            default:
                throw new ArgumentOutOfRangeException(nameof(mode));
        }

        if (degraded is null || !Matches(degraded, original)) {
            return null;
        }

        return new DegradedSource(mode, degraded, TextNormalisation.Lines(degraded).Length, glued);
    }

    /// <summary>⚠ The corpus carries CRLF and BOMs; the degraded corpus is LF and nothing else.</summary>
    /// <remarks>
    /// Line endings are their own measurement (<c>FuzzMutations.LineEndings</c>) and mixing them
    /// into this one would put a whole-file transform with one bit of information in it beside the
    /// wrapping decisions this is trying to see.
    /// </remarks>
    static string Normalise(string source) {
        var text = source.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        return text.StartsWith('﻿') ? text[1..] : text;
    }

    /// <summary>
    /// Whether two texts are the same program: identical token streams under every checked symbol
    /// set, with no new parse error.
    /// </summary>
    /// <remarks>
    /// ⚠ Public so that the committed corpus can be re-checked from its committed bytes rather than
    /// trusted because the generator said so. A degraded input is only half of a fixture pair, and a
    /// hand-edit to either half turns the whole measurement into a comparison of two unrelated
    /// files.
    /// </remarks>
    public static bool IsSameProgram(string original, string degraded) {
        var expected = Fingerprints(Normalise(original));
        return expected is not null && Matches(Normalise(degraded), expected);
    }

    // ── verification ─────────────────────────────────────────────────────────────────────────────

    static bool Matches(string degraded, IReadOnlyList<string> original) {
        var produced = Fingerprints(degraded);
        return produced is not null && produced.SequenceEqual(original, StringComparer.Ordinal);
    }

    /// <summary>One fingerprint per checked symbol set, or <c>null</c> when the text has errors.</summary>
    static List<string>? Fingerprints(string source) {
        var fingerprints = new List<string>(CheckedSymbolSets.Count);
        foreach (var symbols in CheckedSymbolSets) {
            var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), CSharpFormatter.ParseOptionsFor(symbols));
            foreach (var diagnostic in tree.GetDiagnostics()) {
                if (diagnostic.Severity == DiagnosticSeverity.Error) {
                    return null;
                }
            }

            fingerprints.Add(Fingerprint(tree.GetRoot()));
        }

        return fingerprints;
    }

    /// <summary>
    /// Everything in a file that is not whitespace, in order.
    /// </summary>
    /// <remarks>
    /// ⚠ Tokens <em>and</em> non-whitespace trivia. A token stream alone does not see a comment, and
    /// it does not see disabled <c>#if</c> text at all — that text is one
    /// <see cref="SyntaxKind.DisabledTextTrivia"/> and a degradation that ate half of it would
    /// compare equal. Trailing whitespace inside a trivia is trimmed on both sides because neither
    /// mode creates it and no formatter is obliged to keep it.
    /// <para>
    /// ⚠ Disabled text is compared with its whitespace removed, and that relaxation is the
    /// whole reason the fingerprint is taken once <em>per symbol set</em> rather than once. Under
    /// set S, disabled text is not part of the program — it is part of the program under some other
    /// set, and that set has its own fingerprint where the same bytes are live tokens and are
    /// compared exactly. Serilog's <c>TimeProvider.cs</c> is the case that forced this: the entire
    /// file sits under <c>#if !NET8_0_OR_GREATER</c>, so collapsing it is a legitimate degradation
    /// of live code under the empty symbol set and a byte-for-byte rewrite of disabled text under
    /// <see cref="Corpus.PropertySymbols"/>. The relaxation keeps the corruption guard — a deletion
    /// or a reordering still fails — without rejecting the file for being conditional.
    /// </para>
    /// </remarks>
    static string Fingerprint(SyntaxNode root) {
        var builder = new StringBuilder();
        foreach (var token in root.DescendantTokens(descendIntoTrivia: true)) {
            if (token.Span.Length == 0) {
                continue;
            }

            builder.Append(token.RawKind.ToString(CultureInfo.InvariantCulture))
                .Append('')
                .Append(token.Text)
                .Append('');
        }

        foreach (var trivia in root.DescendantTrivia(descendIntoTrivia: true)) {
            if (trivia.IsKind(SyntaxKind.WhitespaceTrivia)
                || trivia.IsKind(SyntaxKind.EndOfLineTrivia)
                || trivia.IsKind(SyntaxKind.DocumentationCommentExteriorTrivia)) {
                continue;
            }

            builder.Append('T')
                .Append(trivia.RawKind.ToString(CultureInfo.InvariantCulture))
                .Append('')
                .Append(
                    trivia.IsKind(SyntaxKind.DisabledTextTrivia)
                        ? Squash(trivia.ToFullString())
                        : TrimTrailingWhitespace(trivia.ToFullString())
                )
                .Append('');
        }

        return builder.ToString();
    }

    /// <summary>Every whitespace character removed.</summary>
    /// <remarks>
    /// ⚠ Removed rather than collapsed to one space, because collapse removes a separator entirely
    /// wherever the two tokens beside it do not need one — Serilog's <c>PropertyBinder.cs</c> has
    /// <c>EventProperty[] ConstructProperties(…)</c> in an <c>#else</c> branch and it comes back as
    /// <c>EventProperty[]ConstructProperties(…)</c>, which is the same program and not the same
    /// number of spaces.
    /// </remarks>
    static string Squash(string text) {
        var builder = new StringBuilder(text.Length);
        foreach (var character in text) {
            if (character is not (' ' or '\t' or '\r' or '\n')) {
                builder.Append(character);
            }
        }

        return builder.ToString();
    }

    static string TrimTrailingWhitespace(string text) {
        var lines = text.Split('\n');
        for (var i = 0; i < lines.Length; i++) {
            lines[i] = lines[i].TrimEnd(' ', '\t', '\r');
        }

        return string.Join('\n', lines).TrimEnd('\n');
    }

    // ── collapse ─────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Rebuilds the file from its token and trivia stream with no line break that the language does
    /// not force.
    /// </summary>
    /// <remarks>
    /// ⚠ Four things force a line: a preprocessor directive, the disabled text between two of them,
    /// a <c>//</c> or <c>///</c> comment (which runs to the end of its line), and the file's end.
    /// Everything else is joined. A file of ordinary C# collapses to one line; a documented one
    /// collapses to one line per <c>///</c> run, which is the honest answer to "as few lines as the
    /// language allows" rather than a softened degradation.
    /// </remarks>
    static string? Collapse(string source, bool alwaysSpace) {
        var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), CSharpFormatter.ParseOptions);
        var root = tree.GetRoot();
        var builder = new StringBuilder(source.Length);
        string? previous = null;

        void Break() {
            if (builder.Length > 0 && builder[^1] != '\n') {
                builder.Append('\n');
            }

            previous = null;
        }

        void Separate(string next) {
            if (builder.Length == 0 || builder[^1] == '\n') {
                return;
            }

            if (previous is null || alwaysSpace || TokenGlue.NeedsSpace(previous, next)) {
                builder.Append(' ');
            }
        }

        void Trivia(SyntaxTrivia trivia) {
            if (trivia.IsKind(SyntaxKind.WhitespaceTrivia) || trivia.IsKind(SyntaxKind.EndOfLineTrivia)) {
                return;
            }

            if (trivia.IsDirective || trivia.IsKind(SyntaxKind.DisabledTextTrivia)) {
                // ⚠ Emitted verbatim and alone on its lines. Disabled text is data — the fuzzer's
                // most expensive lesson — and a directive that is not the first thing on its line
                // is not a directive.
                Break();
                builder.Append(trivia.ToFullString());
                Break();
                return;
            }

            // ⚠ A doc comment gets a line of its own; an ordinary comment does not. `/// …` is
            // attached to a declaration by definition, and `namespace N{ /// <summary>` is not
            // input any tool has ever been handed — it is CS1587 and it would put a class of
            // divergence in the report that no real file can produce. A trailing `// why` after a
            // statement is the opposite: it is exactly what real code carries, and joining the
            // statement onto the line above it is the degradation.
            if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia)
                || trivia.IsKind(SyntaxKind.MultiLineDocumentationCommentTrivia)) {
                Break();
                builder.Append(trivia.ToFullString());
                Break();
                return;
            }

            if (trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)) {
                Separate("//");
                builder.Append(trivia.ToFullString());
                Break();
                return;
            }

            if (trivia.IsKind(SyntaxKind.MultiLineCommentTrivia)) {
                Separate("/*");
                builder.Append(trivia.ToFullString());
                previous = null;
                return;
            }

            // Skipped tokens, a shebang, a conflict marker: keep whatever they are, on their own
            // lines, rather than guessing.
            Break();
            builder.Append(trivia.ToFullString());
            Break();
        }

        // ⚠ An interpolated string is one *node* made of many tokens, and walking it token by token
        // is how a collapse writes a space into a program's output. `$"hello {x}"` decomposes into
        // `$"`, `hello `, `{`, `x`, `}`, `"`, and a separator inserted before the third of those
        // lands inside the string's text. It is the same span `NodeLayout` answers
        // `NodeLayout.Verbatim` for and the same span `FuzzMutations.SourceMap` records as a
        // verbatim region — C# 11 put newlines inside interpolation holes, which is what makes the
        // inside of one reachable at all. Measured before this was here: 277 of 380 files failed the
        // token-stream check, and this was every one of them.
        var verbatim = new List<TextSpan>();
        foreach (var node in root.DescendantNodes()) {
            if (node is InterpolatedStringExpressionSyntax
                && !verbatim.Any(region => region.Contains(node.Span))) {
                verbatim.Add(node.Span);
            }
        }

        TextSpan? RegionAt(int position) {
            foreach (var region in verbatim) {
                if (position >= region.Start && position < region.End) {
                    return region;
                }
            }

            return null;
        }

        foreach (var token in root.DescendantTokens(descendIntoTrivia: false)) {
            var region = token.Span.Length > 0 ? RegionAt(token.SpanStart) : null;
            var inside = region is { } span && token.SpanStart > span.Start;

            if (!inside) {
                foreach (var trivia in token.LeadingTrivia) {
                    Trivia(trivia);
                }
            }

            if (token.Span.Length > 0) {
                if (region is { } whole) {
                    if (token.SpanStart == whole.Start) {
                        var text = source[whole.Start..whole.End];
                        Separate(text);
                        builder.Append(text);
                        previous = text;
                    }
                } else {
                    var text = token.Text;
                    Separate(text);
                    builder.Append(text);
                    previous = text;
                }
            }

            // ⚠ The trailing trivia of the node's *last* token is outside the node's span, so it is
            // emitted even though the token itself was swallowed. Skipping it would eat a comment
            // written after a closing quote.
            if (region is not { } enclosing || token.Span.End >= enclosing.End) {
                foreach (var trivia in token.TrailingTrivia) {
                    Trivia(trivia);
                }
            }
        }

        if (builder.Length > 0 && builder[^1] != '\n') {
            builder.Append('\n');
        }

        return builder.Length == 0 ? null : builder.ToString();
    }

    // ── scramble ─────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Two passes: first the line structure, then the whitespace within it.
    /// </summary>
    /// <remarks>
    /// ⚠ Two passes and two parses, rather than one set of edits. Indentation is a rewrite of a
    /// line's <em>start</em> and a join is a deletion <em>through</em> the next line's start, so a
    /// single-pass version has to either drop overlapping edits silently — which is how a
    /// degradation quietly becomes weaker than it reports — or claim so many lines that most of the
    /// file is left alone. Re-parsing between the two costs one parse per file and makes the second
    /// pass's map describe the text it is actually editing.
    /// </remarks>
    static string? Scramble(string source, FuzzRandom random) {
        var restructured = Restructure(source, random) ?? source;
        return Respace(restructured, random) ?? restructured;
    }

    static string? Restructure(string source, FuzzRandom random) {
        var map = FuzzMutations.SourceMap.Of(source, Corpus.PropertySymbols);

        // ⚠ `absorbing: true` even though these are structural edits. That flag is what folds in the
        // *other* symbol set's disabled text, and a line break moved into the `#else` branch of a
        // file compiled with the `#if` branch is still a line break moved into data.
        var heads = map.SafeLines(atStart: true, absorbing: true).ToHashSet();
        var tails = map.SafeLines(atStart: false, absorbing: true).ToHashSet();
        var claimed = new HashSet<int>();
        var edits = new List<(int Position, int Delete, string Insert)>();

        foreach (var line in map.Joinable) {
            if (!random.Chance(JoinChance)
                || !tails.Contains(line)
                || !heads.Contains(line + 1)
                || claimed.Contains(line)
                || claimed.Contains(line + 1)) {
                continue;
            }

            var span = map.Text.Lines[line];
            var next = map.Text.Lines[line + 1];
            edits.Add((span.End, next.Start + LeadingWhitespace(next.ToString()) - span.End, " "));
            claimed.Add(line);
            claimed.Add(line + 1);
        }

        foreach (var gap in map.AbsorbableGaps) {
            if (!random.Chance(SplitChance)) {
                continue;
            }

            var line = map.Text.Lines.GetLineFromPosition(gap.Start).LineNumber;
            if (claimed.Contains(line)) {
                continue;
            }

            edits.Add((gap.Start, gap.End - gap.Start, "\n"));
            claimed.Add(line);
        }

        foreach (var line in map.LineBoundaries) {
            if (claimed.Contains(line) || !heads.Contains(line)) {
                continue;
            }

            var span = map.Text.Lines[line];
            var blank = span.ToString().Trim().Length == 0 && span.EndIncludingLineBreak > span.End;

            if (blank && random.Chance(BlankRemovalChance)) {
                edits.Add((span.Start, span.EndIncludingLineBreak - span.Start, string.Empty));
                claimed.Add(line);
            } else if (!blank && random.Chance(BlankInsertionChance)) {
                edits.Add((span.Start, 0, "\n"));
                claimed.Add(line);
            }
        }

        return edits.Count == 0 ? null : Splice(source, edits);
    }

    static string? Respace(string source, FuzzRandom random) {
        var map = FuzzMutations.SourceMap.Of(source, Corpus.PropertySymbols);
        var edits = new List<(int Position, int Delete, string Insert)>();

        foreach (var gap in map.AbsorbableGaps) {
            if (!random.Chance(GapChance)) {
                continue;
            }

            // ⚠ Never to zero, for `CollapseGaps`'s reason: `a + +b` with the gap removed
            // re-tokenises to `++`, which is a different program. A gap that was already empty is
            // widened rather than left, which is the other half of "spacing randomised".
            edits.Add((gap.Start, gap.End - gap.Start, new string(' ', random.Next(1, 5))));
        }

        foreach (var line in map.SafeLines(atStart: true, absorbing: true)) {
            if (!random.Chance(IndentChance)) {
                continue;
            }

            var span = map.Text.Lines[line];
            var indent = LeadingWhitespace(span.ToString());
            var replacement = random.Chance(TabChance)
                ? new string('\t', random.Next(0, 4))
                : new string(' ', random.Next(0, 17));

            if (indent > 0 || replacement.Length > 0) {
                edits.Add((span.Start, indent, replacement));
            }
        }

        foreach (var line in map.SafeLines(atStart: false, excludeCommentEnds: true, absorbing: true)) {
            var span = map.Text.Lines[line];
            if (span.End == span.Start || !random.Chance(TrailingChance)) {
                continue;
            }

            edits.Add((span.End, 0, new string(' ', random.Next(1, 4))));
        }

        return edits.Count == 0 ? null : Splice(source, edits);
    }

    /// <summary>
    /// The weights, which are the whole definition of "plausible bad formatting".
    /// </summary>
    /// <remarks>
    /// ⚠ Indentation is drawn hard and joins are drawn softly, and the asymmetry is deliberate.
    /// Indentation carries no information at all — every tool is expected to rebuild it, and a
    /// degradation that leaves it alone is measuring almost nothing. A join or a split *destroys*
    /// author information that <c>keep_user_linebreaks</c> is configured to preserve, so drawing
    /// them at 1 in 3 leaves two thirds of the author's breaks in place, which is what makes this
    /// mode a test of the preserve path rather than a slower collapse.
    /// </remarks>
    const double JoinChance = 0.30;

    const double SplitChance = 0.10;
    const double BlankInsertionChance = 0.07;
    const double BlankRemovalChance = 0.55;
    const double GapChance = 0.35;
    const double IndentChance = 0.80;
    const double TabChance = 0.08;
    const double TrailingChance = 0.10;

    // ── plumbing ─────────────────────────────────────────────────────────────────────────────────

    static int LeadingWhitespace(string line) {
        var indent = 0;
        while (indent < line.Length && line[indent] is ' ' or '\t') {
            indent++;
        }

        return indent;
    }

    /// <summary>
    /// Applies non-overlapping edits, right to left.
    /// </summary>
    /// <remarks>
    /// ⚠ A copy of <c>FuzzMutations.Splice</c>, which is private. Lifted rather than shared because
    /// another agent is working in that file; the two want folding into one helper once both land.
    /// </remarks>
    static string Splice(string source, IReadOnlyList<(int Position, int Delete, string Insert)> edits) {
        var ordered = edits.OrderByDescending(static edit => edit.Position).ToArray();
        var builder = new StringBuilder(source);
        var barrier = source.Length;
        foreach (var edit in ordered) {
            if (edit.Position < 0 || edit.Position + edit.Delete > barrier) {
                continue;
            }

            builder.Remove(edit.Position, edit.Delete);
            builder.Insert(edit.Position, edit.Insert);
            barrier = edit.Position;
        }

        return builder.ToString();
    }
}

/// <summary>
/// Whether two adjacent token texts may be written with nothing between them.
/// </summary>
/// <remarks>
/// ⚠ Answered by lexing rather than by a table of operator pairs, because the table is where the
/// bug lives: <c>1</c> and <c>_2</c> merge, <c>0x1</c> and <c>e5</c> merge, <c>&gt;&gt;&gt;</c> and
/// <c>=</c> merge, and a hand-written list of those is a list somebody forgot a case from.
/// <para>
/// ⚠ The key is a six-character window on each side rather than the whole token, so that a file with
/// four thousand distinct identifiers does not lex four thousand pairs. Truncation can only make the
/// answer <em>more</em> conservative: the check demands that the window lex back to exactly its two
/// halves, and a truncated window that no longer does so answers "needs a space". The longest C#
/// operator is four characters (<c>&gt;&gt;&gt;=</c>), so six is margin rather than a guess.
/// </para>
/// </remarks>
static class TokenGlue {
    const int Window = 6;

    static readonly Dictionary<string, bool> Cache = new(StringComparer.Ordinal);

    public static bool NeedsSpace(string left, string right) {
        var a = left.Length <= Window ? left : left[^Window..];
        var b = right.Length <= Window ? right : right[..Window];
        var key = a + " " + b;
        if (Cache.TryGetValue(key, out var cached)) {
            return cached;
        }

        var needs = !Splits(a, b);
        Cache[key] = needs;
        return needs;
    }

    static bool Splits(string a, string b) {
        var tokens = SyntaxFactory.ParseTokens(a + b)
            .Where(static token => token.Span.Length > 0 && !token.IsKind(SyntaxKind.EndOfFileToken))
            .ToArray();

        return tokens.Length == 2
            && string.Equals(tokens[0].Text, a, StringComparison.Ordinal)
            && string.Equals(tokens[1].Text, b, StringComparison.Ordinal)
            && tokens[0].LeadingTrivia.Count == 0
            && tokens[1].LeadingTrivia.Count == 0;
    }
}
