// <auto-generated/>
// A generator emits the argument order its template holds; it is not a decision made here.
namespace Fixtures {
    sealed class GeneratedMover {
        public void Run(string source, string destination) {
            Copy(destination, source);
        }

        static void Copy(string source, string destination) { }
    }
}
