// <auto-generated/>
// A generator's template and its argument list are written by the same code and move together.
namespace Serilog {
    interface ILogger {
        void Information(string messageTemplate, params object[] propertyValues);
    }
}

namespace Fixtures {
    sealed class GeneratedWorker {
        public void Run(Serilog.ILogger logger, int count) {
            logger.Information("Loaded {Count} of {Total}", count);
        }
    }
}
