// <auto-generated/>
// A generator emits the category its input named; it is not a decision made here.
namespace Microsoft.Extensions.Logging {
    interface ILogger { }

    interface ILogger<out TCategoryName> : ILogger { }
}

namespace Fixtures {
    using Microsoft.Extensions.Logging;

    sealed class PaymentService { }

    sealed class GeneratedOrderService {
        readonly ILogger<PaymentService> logger = null!;

        public override string ToString() => logger.ToString()!;
    }
}
