using Rikarin.Skala.Options;
using Rikarin.Skala.Rules.Metadata;
using System.Globalization;
using System.Text;

namespace Rikarin.Skala.Analysis;

/// <summary>One generated file: a site-relative path with <c>/</c> separators, and its text.</summary>
public readonly record struct DocsPage(string Path, string Content);

/// <summary>
///     <c>skala docs site</c> — the browsable surface of <c>rules.json</c> and <c>options.json</c>.
/// </summary>
/// <remarks>
///     docs/plan/15 § M7, "Documentation site generation from rules.json + options.json", and
///     docs/plan/08 § "Documentation": <em>one source, three surfaces</em>. This is the fourth
///     rendering of the same two registries, not a fourth copy of their text — every string on every
///     page comes from <see cref="RuleCatalog" /> or <see cref="OptionRegistry" />, both of which are
///     generated from the JSON at compile time. There is nothing here to keep in sync by hand, which
///     is the only property that makes a documentation site worth generating at all.
///     <para>
///         ⚠ The output is byte-identical across runs and across machines, because it is committed and
///         diffed (the <c>CloneIndex</c> precedent: "two runs over the same tree produce byte-identical
///         files"). That costs three specific disciplines and each one has been got wrong somewhere:
///     </para>
///     <list type="number">
///         <item>
///             Every newline is a literal <c>\n</c>. <see cref="StringBuilder.AppendLine()" /> emits
///             <see cref="Environment.NewLine" />, so a generator written with it produces CRLF on Windows and
///             LF everywhere else — which is a whole-file diff for a Windows contributor who regenerates.
///             <c>ExplainCommand</c> has this defect today; see <c>DocsSiteTests</c>.
///         </item>
///         <item>
///             Every ordering is <see cref="StringComparer.Ordinal" />. A culture-aware sort puts
///             <c>resharper_csharp_*</c> in a different order under a Turkish locale, and the tool sets
///             <c>InvariantGlobalization</c> only for itself, not for whoever regenerates.
///         </item>
///         <item>
///             Nothing is stamped: no date, no version, no host name. A generated page that carries the
///             moment it was generated cannot be compared with the one in the tree, so the test that keeps it
///             honest cannot exist.
///         </item>
///     </list>
/// </remarks>
public static class DocsSite {
    const string Banner =
        "Generated by `skala docs site` from Rules/Rikarin.Skala.Rules.Metadata/rules.json and "
        + "Core/Rikarin.Skala.Options/options.json. Do not edit.";

    /// <summary>The whole site, in memory, in ordinal path order.</summary>
    public static IReadOnlyList<DocsPage> Render() {
        var rules = RuleCatalog.All.OrderBy(static rule => rule.Id, StringComparer.Ordinal).ToList();
        var options = OptionRegistry.All.OrderBy(static option => option.Key, StringComparer.Ordinal).ToList();

        var constructs = options
            .GroupBy(static option => option.Construct, StringComparer.Ordinal)
            .OrderBy(static group => group.Key, StringComparer.Ordinal)
            .Select(static group => (Construct: group.Key, Options: group.ToList()))
            .ToList();

        var slugOf = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var (construct, _) in constructs) {
            slugOf[construct] = Slug(construct);
        }

        var links = new SiteLinks(slugOf, options, rules);

        var pages = new List<DocsPage> {
            new("style.css", Stylesheet()),
            new("index.html", Landing(rules, options, constructs.Count)),
            new("rules/index.html", RuleIndex(rules)),
            new("options/index.html", OptionIndex(options, constructs, slugOf))
        };

        foreach (var rule in rules) {
            pages.Add(new DocsPage("rules/" + rule.Id + ".html", RulePage(rule, links)));
        }

        foreach (var (construct, members) in constructs) {
            pages.Add(new DocsPage("options/" + slugOf[construct] + ".html", ConstructPage(construct, members, links)));
        }

        pages.Sort(static (a, b) => string.CompareOrdinal(a.Path, b.Path));
        return pages;
    }

    /// <summary>
    ///     Writes the site into <paramref name="directory" /> and returns the number of files written.
    /// </summary>
    /// <remarks>
    ///     ⚠ It deletes generated files the render no longer produces. Without that, a construct
    ///     renamed in options.json leaves its old page behind for ever, still linked from nothing and
    ///     still describing keys that have moved — and the up-to-date test would pass, because it can
    ///     only compare the pages that exist on both sides. Only <c>.html</c> and <c>.css</c> under the
    ///     target are considered; anything else in the directory is somebody's and is left alone.
    /// </remarks>
    public static int Write(string directory) {
        var pages = Render();
        var expected = pages.Select(static page => page.Path).ToHashSet(StringComparer.Ordinal);

        if (Directory.Exists(directory)) {
            foreach (var path in Directory.EnumerateFiles(directory, "*", SearchOption.AllDirectories)
                         .OrderBy(static path => path, StringComparer.Ordinal)) {
                var relative = Relative(directory, path);
                var generated = relative.EndsWith(".html", StringComparison.Ordinal)
                    || relative.EndsWith(".css", StringComparison.Ordinal);
                if (generated && !expected.Contains(relative)) {
                    File.Delete(path);
                }
            }
        }

        foreach (var page in pages) {
            var path = Path.Combine(directory, page.Path.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, page.Content);
        }

        return pages.Count;
    }

    /// <summary>The site-relative path of a file under <paramref name="directory" />, with <c>/</c>.</summary>
    public static string Relative(string directory, string path) =>
        Path.GetRelativePath(directory, path).Replace(Path.DirectorySeparatorChar, '/');

    // ── Pages ────────────────────────────────────────────────────────────────────────────────────

    static string Landing(List<RuleInfo> rules, List<OptionInfo> options, int constructs) {
        var builder = Open("Skala", string.Empty, null);
        builder.Append("<h1>Skala</h1>\n");
        builder.Append(
            """<p class="lede">One configuration, the same formatting and analysis everywhere. This site is the """
            + "rule catalogue and the option registry, rendered from the two files that define them.</p>\n"
        );

        builder.Append("<div class=\"cards\">\n");
        Card(
            builder,
            "rules/index.html",
            "Rules",
            rules.Count,
            "rule" + Plural(rules.Count),
            "What <code>skala check</code> reports, why each finding exists, and what to write instead."
        );
        Card(
            builder,
            "options/index.html",
            "Options",
            options.Count,
            "key" + Plural(options.Count),
            "Every <code>.editorconfig</code> key Skala reads, its default, and how that default is known."
        );
        builder.Append("</div>\n");

        builder.Append("<h2>The rules, by category</h2>\n");
        builder.Append(
            "<div class=\"scroll\">\n<table>\n<thead><tr><th>Category</th><th>Rules</th><th>With a fix</th>"
            + "<th>Run without a project</th></tr></thead>\n<tbody>\n"
        );
        foreach (var group in rules.GroupBy(static rule => rule.Category, StringComparer.Ordinal)
                     .OrderBy(static group => group.Key, StringComparer.Ordinal)) {
            builder.Append("<tr><td>").Append(Esc(group.Key)).Append("</td><td>").Append(Num(group.Count()));
            builder.Append("</td><td>").Append(Num(group.Count(static rule => rule.HasFix)));
            builder.Append("</td><td>").Append(Num(group.Count(static rule => rule.RunsWithoutAProject)));
            builder.Append("</td></tr>\n");
        }

        builder.Append("</tbody>\n</table>\n</div>\n");

        builder.Append("<h2>The options, by tier</h2>\n");
        builder.Append(
            "<p>A tier is a claim about implementation, not about importance. Tier A is read by the formatter "
            + "<em>and</em> pinned by a committed oracle fixture; tier D is recorded so that the key is not "
            + "reported as unknown, and nothing reads it yet.</p>\n"
        );
        builder.Append(
            "<div class=\"scroll\">\n<table>\n<thead><tr><th>Tier</th><th>Keys</th></tr></thead>\n<tbody>\n"
        );
        foreach (var group in options.GroupBy(static option => option.Tier)
                     .OrderBy(static group => group.Key)) {
            builder.Append("<tr><td>").Append(Esc(group.Key.ToString())).Append("</td><td>");
            builder.Append(Num(group.Count())).Append("</td></tr>\n");
        }

        builder.Append("</tbody>\n</table>\n</div>\n");
        builder.Append("""<p class="note">The """)
            .Append(Num(options.Count))
            .Append(" keys are grouped into ")
            .Append(Num(constructs))
            .Append(
                """ constructs; the <a href="options/index.html">option reference</a> is one page per construct, """
                + "with an alphabetical index of every key.</p>\n"
            );

        return Close(builder, string.Empty);
    }

    static string RuleIndex(List<RuleInfo> rules) {
        var builder = Open("Rules — Skala", "../", "rules");
        builder.Append("<h1>Rules</h1>\n");
        builder.Append(
            """<p class="lede"><code>SK</code> + four digits, allocated once and never re-purposed """
            + "(ADR-012). "
        )
            .Append(Num(rules.Count))
            .Append(" ids are allocated.</p>\n");

        foreach (var group in rules.GroupBy(static rule => rule.Category, StringComparer.Ordinal)
                     .OrderBy(static group => group.Key, StringComparer.Ordinal)) {
            builder.Append("<h2 id=\"").Append(Esc(Slug(group.Key))).Append("\">").Append(Esc(group.Key));
            builder.Append("</h2>\n");
            builder.Append(
                "<div class=\"scroll\">\n<table>\n<thead><tr><th>Id</th><th>Rule</th><th>Severity</th><th>Fix</th>"
                + "<th>Loose mode</th></tr></thead>\n<tbody>\n"
            );
            foreach (var rule in group) {
                builder.Append("<tr><td><a href=\"").Append(rule.Id).Append(""".html">""").Append(rule.Id);
                builder.Append("</a></td><td>").Append(Inline(rule.Title));
                if (rule.Retired) {
                    builder.Append(""" <span class="tag retired">retired</span>""");
                }

                builder.Append("</td><td>").Append(SeverityTag(rule));
                builder.Append("</td><td>").Append(rule.HasFix ? rule.FixIsSafe ? "safe" : "review" : "—");
                builder.Append("</td><td>").Append(rule.RunsWithoutAProject ? "yes" : "no");
                builder.Append("</td></tr>\n");
            }

            builder.Append("</tbody>\n</table>\n</div>\n");
        }

        return Close(builder, "../");
    }

    static string RulePage(RuleInfo rule, SiteLinks links) {
        var builder = Open(rule.Id + " — Skala", "../", "rules");
        builder.Append("""<p class="crumb"><a href="index.html">Rules</a> / """).Append(Esc(rule.Category));
        builder.Append("</p>\n");
        builder.Append("<h1>").Append(rule.Id).Append(""" <span class="title">""").Append(Inline(rule.Title));
        builder.Append("</span></h1>\n");

        if (rule.Retired) {
            builder.Append(
                """<p class="banner">⚠ <strong>Retired.</strong> The id stays allocated for ever because every """
                + "baseline in every repository names it (ADR-012), and the analyzer no longer enables it, so "
                + "nothing new is reported. The page is here so that an old finding can still be looked up.</p>\n"
            );
        }

        builder.Append("""<p class="lede">""").Append(Inline(rule.Summary)).Append("</p>\n");

        builder.Append("<table class=\"facts\">\n<tbody>\n");
        Fact(builder, "Category", Esc(rule.Category));
        Fact(builder, "Default severity", SeverityTag(rule));
        Fact(builder, "Scope", Esc(rule.Scope.ToString()));
        Fact(builder, "Needs a compilation", rule.RequiresSemantics ? "yes" : "no");
        Fact(builder, "Runs under <code>--load=loose</code>", rule.RunsWithoutAProject ? "yes" : "no");
        Fact(builder, "Cached per file", rule.IsCacheable ? "yes" : "no — it reads the whole compilation");
        Fact(builder, "Fix", rule.HasFix ? rule.FixIsSafe ? "yes, safe" : "yes, review it" : "no");
        Fact(builder, "Language version floor", rule.LanguageVersion is { } floor ? "C# " + Esc(floor) : "—");
        Fact(builder, "Since", Esc(rule.Since));
        if (rule.Supersedes.Count > 0) {
            Fact(builder, "Supersedes", string.Join(", ", rule.Supersedes.Select(Esc)));
        }

        builder.Append("</tbody>\n</table>\n");

        builder.Append("<h2 id=\"why\">Why</h2>\n");
        Prose(builder, rule.Rationale);

        if (rule.BadExample.Length > 0 || rule.GoodExample.Length > 0) {
            builder.Append("<h2 id=\"example\">Example</h2>\n");
            if (rule.BadExample.Length > 0) {
                builder.Append("<p>Instead of:</p>\n<pre class=\"bad\"><code>").Append(Esc(rule.BadExample));
                builder.Append("</code></pre>\n");
            }

            if (rule.GoodExample.Length > 0) {
                builder.Append("<p>Write:</p>\n<pre class=\"good\"><code>").Append(Esc(rule.GoodExample));
                builder.Append("</code></pre>\n");
            }
        }

        builder.Append("<h2 id=\"false-positives\">When it does not fire</h2>\n");
        Prose(builder, rule.FalsePositives);

        if (rule.Configuration.Count > 0) {
            builder.Append("<h2 id=\"configuration\">Configuration</h2>\n<ul class=\"config\">\n");
            foreach (var entry in rule.Configuration) {
                builder.Append("<li>").Append(links.Linkify(entry, "../", rule.Id)).Append("</li>\n");
            }

            builder.Append("</ul>\n");
        }

        return Close(builder, "../");
    }

    static string OptionIndex(
        List<OptionInfo> options,
        List<(string Construct, List<OptionInfo> Options)> constructs,
        Dictionary<string, string> slugOf
    ) {
        var builder = Open("Options — Skala", "../", "options");
        builder.Append("<h1>Options</h1>\n");
        builder.Append("""<p class="lede">""")
            .Append(Num(options.Count))
            .Append(" <code>.editorconfig</code> keys, grouped into ")
            .Append(Num(constructs.Count))
            .Append(" constructs the way ReSharper's own settings pages group them.</p>\n");

        builder.Append("<h2 id=\"constructs\">By construct</h2>\n");
        builder.Append(
            "<div class=\"scroll\">\n<table>\n<thead><tr><th>Construct</th><th>Keys</th><th>Tier A</th>"
            + "<th>Languages</th></tr></thead>\n<tbody>\n"
        );
        foreach (var (construct, members) in constructs) {
            var languages = members.Select(static option => option.Language)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static language => language, StringComparer.Ordinal);
            builder.Append("<tr><td><a href=\"").Append(Esc(slugOf[construct])).Append(""".html">""");
            builder.Append(Esc(Spaced(construct))).Append("</a></td><td>").Append(Num(members.Count));
            builder.Append("</td><td>").Append(Num(members.Count(static option => option.Tier == OptionTier.A)));
            builder.Append("</td><td>").Append(Esc(string.Join(", ", languages))).Append("</td></tr>\n");
        }

        builder.Append("</tbody>\n</table>\n</div>\n");

        builder.Append("<h2 id=\"keys\">Every key</h2>\n");
        builder.Append("<p>Ordinal order, which is the order the registry assigns ids in.</p>\n");
        builder.Append("<ul class=\"keys\">\n");
        foreach (var option in options) {
            builder.Append("<li><a href=\"")
                .Append(Esc(slugOf[option.Construct]))
                .Append(".html#")
                .Append(Esc(option.Key))
                .Append("\"><code>")
                .Append(Esc(option.Key))
                .Append("</code></a></li>\n");
        }

        builder.Append("</ul>\n");
        return Close(builder, "../");
    }

    static string ConstructPage(string construct, List<OptionInfo> members, SiteLinks links) {
        var builder = Open(Spaced(construct) + " — Skala options", "../", "options");
        builder.Append("<p class=\"crumb\"><a href=\"index.html\">Options</a></p>\n");
        builder.Append("<h1>").Append(Esc(Spaced(construct))).Append("</h1>\n");
        builder.Append("""<p class="lede">""")
            .Append(Num(members.Count))
            .Append(" key")
            .Append(Plural(members.Count))
            .Append(".</p>\n");

        foreach (var option in members) {
            builder.Append("<section class=\"option\" id=\"").Append(Esc(option.Key)).Append("\">\n");
            builder.Append("<h2><code>").Append(Esc(option.Key)).Append("""</code> <a class="self" href="#""");
            builder.Append(Esc(option.Key)).Append("\">#</a></h2>\n");
            if (option.Summary.Length > 0) {
                builder.Append("<p>").Append(Inline(option.Summary)).Append("</p>\n");
            }

            builder.Append("<table class=\"facts\">\n<tbody>\n");
            Fact(builder, "Type", TypeOf(option));
            Fact(
                builder,
                "Default",
                option.Default is { Length: > 0 } value ? Code(value) : "—"
            );
            Fact(builder, "Default known from", DefaultSourceText(option.DefaultSource));
            Fact(builder, "Tier", TierText(option.Tier));
            Fact(builder, "Language", Esc(option.Language));
            Fact(builder, "Since", Esc(option.Since));
            if (option.Aliases.Count > 0) {
                Fact(
                    builder,
                    "Also spelled",
                    string.Join(", ", option.Aliases.Select(static alias => Code(alias)))
                );
            }

            if (option.SeveritySuffix) {
                Fact(builder, "Severity suffix", "accepted — <code>key = value:suggestion</code>");
            }

            if (option.Expands.Count > 0) {
                var expanded = option.Expands
                    .Select(static id => OptionRegistry.Get(id).Key)
                    .OrderBy(static key => key, StringComparer.Ordinal)
                    .Select(key => links.KeyLink(key, "../"));
                Fact(builder, "Expands to", string.Join(", ", expanded));
            }

            if (option.Oracle is { Length: > 0 } oracle) {
                Fact(builder, "Oracle fixture", Code(oracle));
            }

            var readers = links.RulesReading(option.Key);
            if (readers.Count > 0) {
                Fact(
                    builder,
                    "Read by",
                    string.Join(
                        ", ",
                        readers.Select(static id => """<a href="../rules/""" + id + """.html">""" + id + "</a>")
                    )
                );
            }

            // ⚠ No "Documented at" row, and nothing replaced it. This page is the documentation now.
            // The row pointed 368 of 436 options at jetbrains.com, at a page describing the key under
            // the export's own name — the one spelling Skala does not read — so following it landed a
            // reader on advice about a different tool's configuration.
            builder.Append("</tbody>\n</table>\n</section>\n");
        }

        return Close(builder, "../");
    }

    // ── The shell ────────────────────────────────────────────────────────────────────────────────

    static StringBuilder Open(string title, string root, string? active) {
        var builder = new StringBuilder(4096);
        builder.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
        builder.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        builder.Append("<title>").Append(Esc(title)).Append("</title>\n");
        builder.Append("<link rel=\"stylesheet\" href=\"").Append(root).Append("style.css\">\n");
        builder.Append("</head>\n<body>\n<!-- ").Append(Esc(Banner)).Append(" -->\n");
        builder.Append("<nav><a class=\"brand\" href=\"").Append(root).Append("""index.html">Skala</a>""");
        Tab(builder, root + "rules/index.html", "Rules", active == "rules");
        Tab(builder, root + "options/index.html", "Options", active == "options");
        builder.Append("</nav>\n<main>\n");
        return builder;
    }

    static string Close(StringBuilder builder, string root) {
        builder.Append("</main>\n<footer>Generated from <code>rules.json</code> and <code>options.json</code> by ");
        builder.Append("<code>skala docs site</code>. Editing a page here edits nothing: the next regeneration ");
        builder.Append("overwrites it, and <code>DocsSiteTests</code> fails until it does. ");
        builder.Append("<a href=\"").Append(root).Append("index.html\">Home</a></footer>\n</body>\n</html>\n");
        return builder.ToString();
    }

    static void Tab(StringBuilder builder, string href, string text, bool active) {
        builder.Append("""<a class="tab""").Append(active ? " active" : string.Empty).Append("\" href=\"");
        builder.Append(href).Append("\">").Append(text).Append("</a>");
    }

    static void Card(StringBuilder builder, string href, string title, int count, string unit, string blurb) {
        builder.Append("<a class=\"card\" href=\"").Append(href).Append("\"><span class=\"count\">");
        builder.Append(Num(count)).Append("""</span><span class="unit">""").Append(Esc(unit));
        builder.Append("</span><strong>").Append(Esc(title)).Append("""</strong><span class="blurb">""");
        builder.Append(blurb).Append("</span></a>\n");
    }

    static void Fact(StringBuilder builder, string name, string valueHtml) =>
        builder.Append("<tr><th>").Append(name).Append("</th><td>").Append(valueHtml).Append("</td></tr>\n");

    /// <summary>Paragraphs, split on a blank line. The fields are prose, and some of them are long.</summary>
    static void Prose(StringBuilder builder, string text) {
        foreach (var paragraph in text.Replace("\r\n", "\n", StringComparison.Ordinal)
                     .Split("\n\n", StringSplitOptions.RemoveEmptyEntries)) {
            var joined = string.Join(" ", paragraph.Split('\n', StringSplitOptions.RemoveEmptyEntries));
            if (joined.Trim().Length == 0) {
                continue;
            }

            builder.Append("<p>").Append(Inline(joined.Trim())).Append("</p>\n");
        }
    }

    // ── Text ─────────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     HTML-escapes, and drops <c>\r</c>.
    /// </summary>
    /// <summary>One escaped span of code, which is seven of this file's eight <c>&lt;code&gt;</c> tags.</summary>
    /// <remarks>
    ///     ⚠ Extracted because <c>SK7083</c> reported the literal eight times against a threshold of
    ///     five, and the honest answer to Skala's own rule is the rule's own remedy rather than a
    ///     baseline entry. The eighth is <see cref="Anchors" />' <c>Append</c> pair, which writes a
    ///     substring of an already-escaped buffer and so cannot call this.
    /// </remarks>
    static string Code(string text) => "<code>" + Esc(text) + "</code>";

    /// <remarks>
    ///     ⚠ The dropped carriage return is the second half of the CRLF hazard the stylesheet's remarks
    ///     describe, and this is the choke point for it: <c>rules.json</c> and <c>options.json</c> reach
    ///     the registries as string literals emitted by a source generator from the files' own bytes, so
    ///     a CRLF checkout puts <c>\r</c> inside a rationale, and every text on every page passes
    ///     through here on its way to the output.
    /// </remarks>
    static string Esc(string text) {
        var builder = new StringBuilder(text.Length + 16);
        foreach (var c in text) {
            switch (c) {
                case '\r':
                    break;
                case '&':
                    builder.Append("&amp;");
                    break;
                case '<':
                    builder.Append("&lt;");
                    break;
                case '>':
                    builder.Append("&gt;");
                    break;
                case '"':
                    builder.Append("&quot;");
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.ToString();
    }

    /// <summary>
    ///     The two inline markdown spellings the two registries actually use: <c>`code`</c> and
    ///     <c>**bold**</c>.
    /// </summary>
    /// <remarks>
    ///     ⚠ Escaping happens first and the markers are matched in the escaped text, which is safe only
    ///     because escaping introduces neither a backtick nor an asterisk. Reversing the two would let a
    ///     <c>&lt;</c> inside a code span reach the page as markup.
    /// </remarks>
    static string Inline(string text) {
        var escaped = Esc(text);
        var builder = new StringBuilder(escaped.Length + 32);
        var i = 0;
        while (i < escaped.Length) {
            if (escaped[i] == '`') {
                var end = escaped.IndexOf('`', i + 1);
                if (end > i) {
                    builder.Append("<code>").Append(escaped, i + 1, end - i - 1).Append("</code>");
                    i = end + 1;
                    continue;
                }
            }

            if (escaped[i] == '*' && i + 1 < escaped.Length && escaped[i + 1] == '*') {
                var end = escaped.IndexOf("**", i + 2, StringComparison.Ordinal);
                if (end > i) {
                    builder.Append("<strong>").Append(escaped, i + 2, end - i - 2).Append("</strong>");
                    i = end + 2;
                    continue;
                }
            }

            if (escaped[i] == '*' && Opens(escaped, i)) {
                var end = Closes(escaped, i + 1);
                if (end > i) {
                    builder.Append("<em>").Append(escaped, i + 1, end - i - 1).Append("</em>");
                    i = end + 1;
                    continue;
                }
            }

            builder.Append(escaped[i]);
            i++;
        }

        return builder.ToString();
    }

    /// <summary>Whether the <c>*</c> at <paramref name="i" /> opens an emphasis span.</summary>
    /// <remarks>
    ///     ⚠ The test is left-flanking rather than "is an asterisk", and the catalogue is the reason:
    ///     SK0001's configuration entry reads "Every <c>resharper_*</c> formatting key" and SK8005's
    ///     false-positive note contains <c>[**/*.Tests/**/*.cs]</c>. Naive pairing opens an emphasis at
    ///     the first of those and closes it wherever the next asterisk happens to be. An opener follows
    ///     a space and precedes a non-space; a closer does the reverse.
    /// </remarks>
    static bool Opens(string text, int i) =>
        (i == 0 || char.IsWhiteSpace(text[i - 1]) || text[i - 1] is '(' or '—')
        && i + 1 < text.Length
        && !char.IsWhiteSpace(text[i + 1]);

    static int Closes(string text, int from) {
        for (var j = from + 1; j < text.Length; j++) {
            if (text[j] == '*' && !char.IsWhiteSpace(text[j - 1])) {
                return j;
            }
        }

        return -1;
    }

    static string SeverityTag(RuleInfo rule) {
        var severity = rule.DefaultSeverity.ToString().ToLowerInvariant();
        return """<span class="tag sev-""" + severity + "\">" + severity + "</span>";
    }

    static string TypeOf(OptionInfo option) =>
        option.Kind switch {
            OptionValueKind.Bool => "<code>true</code> / <code>false</code>",
            OptionValueKind.Int => "integer",
            OptionValueKind.Enum or OptionValueKind.Flags => EnumValues(option),
            _ => "string"
        };

    static string EnumValues(OptionInfo option) {
        var values = OptionEnums.ValuesOf(option.EnumName ?? string.Empty);
        var rendered = string.Join(
            ", ",
            values.Select(static value => Code(value))
        );
        var prefix = option.Kind == OptionValueKind.Flags
            ? "any combination, comma-separated, of "
            : "one of ";
        return values.Length == 0 ? "string" : prefix + rendered;
    }

    static string DefaultSourceText(OptionDefaultSource source) =>
        source switch {
            OptionDefaultSource.ReSharperDocs => "JetBrains' published tables",
            OptionDefaultSource.OracleProbe =>
                "an oracle probe — <code>jb cleanupcode</code> under a configuration carrying nothing but "
                + "<code>root = true</code>, compared against the fixture that exercises the key",
            OptionDefaultSource.Template =>
                "the Rider export, which is Rider's default for most keys and the author's choice for the rest, "
                + "with nothing distinguishing the two",
            _ => "nothing beyond the export"
        };

    static string TierText(OptionTier tier) =>
        tier switch {
            OptionTier.A => "A — the formatter reads it and a committed oracle fixture pins it",
            OptionTier.B => "B — the formatter reads it; no fixture pins it yet",
            OptionTier.C => "C — recorded, and it configures a language Skala does not format",
            _ => "D — recorded so the key is not reported unknown; nothing reads it yet"
        };

    /// <summary><c>ArrangementOfLINQExpressions</c> → <c>arrangement-of-linq-expressions</c>.</summary>
    /// <remarks>
    ///     ⚠ A run of capitals is one word, on the same argument <see cref="RuleInfo" />'s snake-caser
    ///     makes: <c>LINQ</c> is <c>linq</c> and not <c>l-i-n-q</c>. The 107 constructs produce 107
    ///     distinct slugs, and <c>DocsSiteTests</c> asserts it rather than trusting it — two constructs
    ///     colliding would silently drop one page's worth of keys.
    /// </remarks>
    static string Slug(string name) {
        var builder = new StringBuilder(name.Length + 8);
        for (var i = 0; i < name.Length; i++) {
            var c = name[i];
            if (!char.IsLetterOrDigit(c)) {
                if (builder.Length > 0 && builder[^1] != '-') {
                    builder.Append('-');
                }

                continue;
            }

            if (char.IsUpper(c)) {
                var startsWord = i > 0
                    && (!char.IsUpper(name[i - 1]) || i + 1 < name.Length && char.IsLower(name[i + 1]));
                if (startsWord && builder.Length > 0 && builder[^1] != '-') {
                    builder.Append('-');
                }
            }

            builder.Append(char.ToLowerInvariant(c));
        }

        return builder.ToString().Trim('-');
    }

    /// <summary><c>BlankLinesInDeclarations</c> → <c>Blank lines in declarations</c>, for a heading.</summary>
    static string Spaced(string name) {
        var slug = Slug(name).Replace('-', ' ');
        return slug.Length == 0 ? name : char.ToUpperInvariant(slug[0]) + slug[1..];
    }

    static string Num(int value) => value.ToString(CultureInfo.InvariantCulture);

    static string Plural(int count) => count == 1 ? string.Empty : "s";

    // ── Cross-links ──────────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The two directions of the rule ↔ option edge, and the only part of the site that is inferred
    ///     rather than copied.
    /// </summary>
    /// <remarks>
    ///     ⚠ <c>rules.json</c>'s <c>configuration</c> is prose, not a list of keys — entries read
    ///     "<c>dotnet_code_quality.SK7001.threshold (default 25)</c>" and "Every <c>resharper_*</c>
    ///     formatting key; the finding is whatever the configured formatter does". So the edge is
    ///     recovered by scanning each entry for the longest runs of key characters and asking the
    ///     registry whether one of them is a key it knows. Anything unrecognised is left as text, which
    ///     is why an unlinked entry is a normal outcome here and not a defect.
    /// </remarks>
    sealed class SiteLinks {
        readonly Dictionary<string, string> slugOf;
        readonly Dictionary<string, string> constructOf = new(StringComparer.Ordinal);
        readonly HashSet<string> ruleIds = new(StringComparer.Ordinal);
        readonly Dictionary<string, SortedSet<string>> readers = new(StringComparer.Ordinal);
        static readonly SortedSet<string> Empty = new(StringComparer.Ordinal);

        public SiteLinks(
            Dictionary<string, string> slugOf,
            List<OptionInfo> options,
            List<RuleInfo> rules
        ) {
            this.slugOf = slugOf;
            foreach (var option in options) {
                constructOf[option.Key] = option.Construct;
            }

            foreach (var rule in rules) {
                ruleIds.Add(rule.Id);
            }

            foreach (var rule in rules) {
                foreach (var entry in rule.Configuration) {
                    foreach (var token in Tokens(entry)) {
                        if (Canonical(token) is not { } key) {
                            continue;
                        }

                        if (!readers.TryGetValue(key, out var set)) {
                            set = new(StringComparer.Ordinal);
                            readers[key] = set;
                        }

                        set.Add(rule.Id);
                    }
                }
            }
        }

        public SortedSet<string> RulesReading(string key) => readers.TryGetValue(key, out var set) ? set : Empty;

        /// <summary>An anchor to the key's entry on its construct page.</summary>
        public string KeyLink(string key, string root) {
            if (!constructOf.TryGetValue(key, out var construct)) {
                return Code(key);
            }

            return "<a href=\""
                + root
                + "options/"
                + Esc(slugOf[construct])
                + ".html#"
                + Esc(key)
                + "\"><code>"
                + Esc(key)
                + "</code></a>";
        }

        /// <summary>
        ///     One <c>configuration</c> entry, with every option key and every rule id it mentions
        ///     turned into a link and everything else escaped.
        /// </summary>
        /// <remarks>
        ///     ⚠ A backtick span is consumed whole, before tokenisation. The entries are written in
        ///     inline markdown — SK3001's is "<c>`none` by default; set it to `warning` to enable</c>"
        ///     — and a tokeniser that walks past a backtick one character at a time never sees a pair
        ///     and puts both on the page as literal text. That is what the first version of this did.
        ///     <para>
        ///         The emphasis <see cref="Inline" /> understands is deliberately not applied here: an
        ///         asterisk in a configuration entry is <c>resharper_*</c>, a glob and never emphasis.
        ///     </para>
        /// </remarks>
        public string Linkify(string entry, string root, string? selfId) {
            var builder = new StringBuilder(entry.Length + 64);
            var i = 0;
            while (i < entry.Length) {
                if (entry[i] == '`') {
                    var end = entry.IndexOf('`', i + 1);
                    if (end > i) {
                        builder.Append(Token(entry[(i + 1)..end], root, selfId, true));
                        i = end + 1;
                        continue;
                    }
                }

                if (IsTokenChar(entry[i])) {
                    var start = i;
                    while (i < entry.Length && IsTokenChar(entry[i])) {
                        i++;
                    }

                    builder.Append(Token(entry[start..i], root, selfId, false));
                    continue;
                }

                var run = i;
                while (i < entry.Length && !IsTokenChar(entry[i]) && entry[i] != '`') {
                    i++;
                }

                builder.Append(Esc(entry[run..i]));
            }

            return builder.ToString();
        }

        /// <summary>One token: an option key, a rule id, or neither.</summary>
        /// <remarks>
        ///     ⚠ <paramref name="selfId" /> suppresses the link and keeps the markup. Every rule's
        ///     configuration list opens with <c>dotnet_diagnostic.SK….severity</c>, and a page whose
        ///     first link goes to the page it is already on is how a reader learns to stop following
        ///     the links.
        /// </remarks>
        string Token(string text, string root, string? selfId, bool code) {
            if (Canonical(text) is { } key) {
                return KeyLink(key, root);
            }

            if (RuleIdIn(text) is { } id) {
                var rendered = Code(text);
                return string.Equals(id, selfId, StringComparison.Ordinal)
                    ? rendered
                    : "<a href=\"" + root + "rules/" + id + """.html">""" + rendered + "</a>";
            }

            return code ? Code(text) : Esc(text);
        }

        /// <summary>The canonical key for any spelling ReSharper accepts, or null.</summary>
        string? Canonical(string token) =>
            OptionRegistry.TryResolve(token, out var id) && constructOf.ContainsKey(OptionRegistry.Get(id).Key)
                ? OptionRegistry.Get(id).Key
                : null;

        /// <summary>
        ///     <c>dotnet_diagnostic.SK1005.severity</c> and
        ///     <c>dotnet_code_quality.SK7001.threshold</c> both name a rule; the id is the dotted part
        ///     the catalogue knows.
        /// </summary>
        string? RuleIdIn(string token) {
            foreach (var part in token.Split('.')) {
                if (ruleIds.Contains(part)) {
                    return part;
                }
            }

            return null;
        }

        static IEnumerable<string> Tokens(string entry) {
            var i = 0;
            while (i < entry.Length) {
                if (!IsTokenChar(entry[i])) {
                    i++;
                    continue;
                }

                var start = i;
                while (i < entry.Length && IsTokenChar(entry[i])) {
                    i++;
                }

                yield return entry[start..i];
            }
        }

        static bool IsTokenChar(char c) => char.IsLetterOrDigit(c) || c is '_' or '.';
    }

    // ── The stylesheet ───────────────────────────────────────────────────────────────────────────

    /// <summary>
    ///     The one stylesheet, inlined here rather than checked in beside the pages.
    /// </summary>
    /// <remarks>
    ///     ⚠ No external asset of any kind — no font, no script, no CDN. The site has to render from a
    ///     checkout with no network, which is the state a reader is in when they are offline on a train
    ///     with the repository and a question about SK7020.
    ///     <para>
    ///         ⚠ The <c>\r\n</c> strip is not decoration. A raw string literal carries the source file's own
    ///         line endings, and <c>.gitattributes</c> marks only the corpus and the fixtures <c>-text</c> —
    ///         so a Windows checkout under git's default <c>core.autocrlf=true</c> gives this file CRLF, and
    ///         the stylesheet would then differ by 60 lines depending on who regenerated it. Every other
    ///         newline in the site is a literal <c>\n</c> written by this class; this is the one the
    ///         compiler supplies.
    ///     </para>
    /// </remarks>
    static string Stylesheet() => Css.Replace("\r\n", "\n", StringComparison.Ordinal);

    const string Css =
        """
        /* Generated by `skala docs site`. Do not edit. */
        :root {
          --bg: #fdfdfc; --fg: #1c1b19; --dim: #6a6862; --line: #e2e0da;
          --accent: #7a4b1e; --code-bg: #f2f0eb; --bad: #b3261e; --good: #2c6e35;
        }
        @media (prefers-color-scheme: dark) {
          :root {
            --bg: #171614; --fg: #e8e6e1; --dim: #9d9a92; --line: #33312c;
            --accent: #d9a066; --code-bg: #22201d; --bad: #f2b8b5; --good: #9bd4a2;
          }
        }
        * { box-sizing: border-box; }
        body {
          margin: 0; background: var(--bg); color: var(--fg);
          font: 16px/1.6 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
        }
        nav {
          display: flex; align-items: baseline; gap: 1.25rem; padding: 0.85rem 1.5rem;
          border-bottom: 1px solid var(--line); position: sticky; top: 0; background: var(--bg);
        }
        nav .brand { font-weight: 700; letter-spacing: 0.02em; }
        nav a { color: var(--fg); text-decoration: none; }
        nav .tab { color: var(--dim); }
        nav .tab.active, nav a:hover { color: var(--accent); }
        main { max-width: 52rem; margin: 0 auto; padding: 2rem 1.5rem 4rem; }
        h1 { font-size: 1.9rem; line-height: 1.25; margin: 0 0 0.5rem; overflow-wrap: anywhere; }
        h1 .title { font-weight: 400; color: var(--dim); }
        h2 { font-size: 1.25rem; margin: 2.25rem 0 0.75rem; }
        a { color: var(--accent); }
        /* ⚠ `overflow-wrap: anywhere` on inline code, and explicitly *not* inside a `pre`. A rule's
           prose names things like `resharper_use_throw_if_null_method_highlighting` and
           `ArgumentNullException.ThrowIfNull` mid-sentence; unbroken, those push the document past
           the viewport on a phone. A code *block* must not break — broken C# is unreadable and
           uncopyable — so it scrolls in its own box instead. */
        code {
          font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
          font-size: 0.9em; background: var(--code-bg); padding: 0.1em 0.32em; border-radius: 3px;
          overflow-wrap: anywhere;
        }
        pre { background: var(--code-bg); padding: 0.9rem 1rem; border-radius: 5px; overflow-x: auto; }
        pre code {
          background: none; padding: 0; font-size: 0.86rem; line-height: 1.5; overflow-wrap: normal;
        }
        pre.bad { border-left: 3px solid var(--bad); }
        pre.good { border-left: 3px solid var(--good); }
        p.lede { font-size: 1.05rem; color: var(--dim); margin-top: 0; }
        p.crumb { color: var(--dim); font-size: 0.85rem; margin: 0 0 0.75rem; }
        p.note { color: var(--dim); font-size: 0.9rem; }
        p.banner { border-left: 3px solid var(--bad); padding: 0.5rem 0.9rem; background: var(--code-bg); }
        /* ⚠ An index table scrolls inside its own box; the document never scrolls sideways. The
           rules index is five columns wide and one of them is a rule title, so on a phone it is
           wider than the viewport no matter what — and a body that scrolls horizontally hides the
           navigation as soon as it does. */
        .scroll { overflow-x: auto; }
        table { border-collapse: collapse; width: 100%; margin: 0.5rem 0 1rem; font-size: 0.92rem; }
        th, td { text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid var(--line); }
        th { color: var(--dim); font-weight: 600; }
        /* ⚠ `table-layout: fixed` plus `anywhere`: an option's `docs` URL is one token with no break
           opportunity — the longest are 132 characters — and 453 of the 520 keys carry one. Left to
           itself the table widens past the viewport and every option page scrolls sideways. */
        table.facts { table-layout: fixed; }
        table.facts th { width: 32%; vertical-align: top; }
        table.facts td { overflow-wrap: anywhere; }
        .tag {
          display: inline-block; font-size: 0.78rem; padding: 0.05em 0.45em; border-radius: 3px;
          background: var(--code-bg); border: 1px solid var(--line);
        }
        .tag.sev-error, .tag.retired { color: var(--bad); }
        .tag.sev-none { color: var(--dim); }
        .tag.sev-warning { color: var(--accent); }
        .cards { display: flex; flex-wrap: wrap; gap: 1rem; margin: 1.5rem 0; }
        .card {
          flex: 1 1 16rem; border: 1px solid var(--line); border-radius: 6px; padding: 1rem 1.1rem;
          text-decoration: none; color: var(--fg); display: block;
        }
        .card:hover { border-color: var(--accent); }
        .card .count { font-size: 2rem; font-weight: 700; line-height: 1; }
        .card .unit { color: var(--dim); font-size: 0.85rem; margin-left: 0.4rem; }
        .card strong { display: block; margin-top: 0.5rem; }
        .card .blurb { display: block; color: var(--dim); font-size: 0.88rem; margin-top: 0.25rem; }
        ul.keys { columns: 2 20rem; list-style: none; padding: 0; font-size: 0.88rem; }
        /* ⚠ The longest key is 81 characters — resharper_csharp_keep_existing_primary_constructor_
           declaration_parens_arrangement — and a monospace run that long has no break opportunity,
           so without this the "Every key" list widens the page and the whole document scrolls. */
        ul.keys li { break-inside: avoid; margin-bottom: 0.15rem; overflow-wrap: anywhere; }
        ul.config li { margin-bottom: 0.35rem; overflow-wrap: anywhere; }
        section.option { margin-top: 2rem; padding-top: 0.5rem; border-top: 1px solid var(--line); }
        section.option h2 { margin-top: 0; font-size: 1.05rem; overflow-wrap: anywhere; }
        section.option h2 code { background: none; padding: 0; font-size: 1em; }
        a.self { color: var(--line); text-decoration: none; font-weight: 400; }
        section.option:hover a.self { color: var(--dim); }
        footer {
          max-width: 52rem; margin: 0 auto; padding: 1.25rem 1.5rem 3rem;
          border-top: 1px solid var(--line); color: var(--dim); font-size: 0.85rem;
        }

        """;
}
