namespace Rikarin.Skala.Core;

/// <summary>
///     The one place <c>&lt;repo&gt;/.skala/</c> is created, and the reason it does not show up in
///     <c>git status</c>.
/// </summary>
/// <remarks>
///     ⚠ <b>This type exists because the tool was dirtying the repositories it ran on.</b> Six call
///     sites created <c>.skala/</c> — the daemon socket, the diagnostic cache, the clone index, the
///     SARIF report, the crash artefacts and the conformance summary — and not one of them left
///     anything behind to keep git quiet. A run of <c>skala check</c> on somebody else's tree added
///     <c>.skala/cache/</c> to their working copy, and an earlier measurement run left exactly that
///     inside the Vixen checkout. A tool that dirties the host repository's <c>git status</c> is a tool
///     people stop running, and the failure is worse than noisy: it is attributed to whatever the
///     person was actually doing.
///     <para>
///         The fix is that the directory ignores itself. Whenever it is created, a <c>.gitignore</c> goes
///         in beside the contents, so the directory is invisible to git without the host repository having
///         to know Skala exists, and without Skala editing a file it does not own. The host's own
///         <c>.gitignore</c> is never touched — writing into a file the user maintains is how a tool earns
///         a merge conflict.
///     </para>
///     <para>
///         ⚠ <b>One file is an exception, and it is the reason the marker is not just <c>*</c>.</b>
///         <c>baseline.sarif</c> is the only thing under <c>.skala/</c> that is not scratch. docs/plan/09
///         calls it "a reviewed, committed artefact — its diff in a PR is 'we suppressed these'", and doc
///         09's own <c>ci</c> gate names <c>.skala/baseline.sarif</c>. A marker of <c>*</c> meant the tool
///         wrote the baseline and then ignored it: the first repository to adopt Skala had to
///         <c>git add -f</c> the artefact the design says must be committed, and a baseline nobody commits
///         is a baseline the gate cannot read on the next machine. Everything else here — <c>cache/</c>,
///         <c>crash/</c>, <c>report.sarif</c>, <c>history.jsonl</c>, the daemon socket — stays ignored.
///     </para>
///     <para>
///         ⚠ <b>The marker still hides itself</b>, and the tempting <c>!.gitignore</c> beside the baseline
///         line is wrong. Un-ignoring it would put <c>?? .skala/.gitignore</c> in the <c>git status</c> of
///         every repository Skala is ever run in, which is precisely the failure above. Nothing is lost:
///         the file is regenerated by whichever clone runs Skala first, and a <em>tracked</em> baseline
///         stays tracked no matter what any ignore file says.
///     </para>
///     <para>
///         ⚠ Nothing here throws. Every caller is on a path where failing to write a hygiene marker is
///         strictly less bad than failing the operation the user asked for — a read-only checkout still
///         gets its analysis, it just does not get the marker.
///     </para>
/// </remarks>
public static class SkalaDirectory {
    /// <summary>The directory's name under the repository root.</summary>
    public const string Name = ".skala";

    /// <summary>
    ///     What the marker contains: everything here is Skala's scratch, except the baseline — which is
    ///     the user's, and is meant to be committed and reviewed — and the marker itself.
    /// </summary>
    public const string IgnoreContents = "*\n!baseline.sarif\n";

    /// <summary>
    ///     The marker as it was written before M9: a bare <c>*</c>, which also swallowed
    ///     <c>baseline.sarif</c>. <see cref="Mark" /> upgrades a file with exactly these bytes and
    ///     leaves anything else alone, so a repository that adopted Skala earlier stops needing
    ///     <c>git add -f</c> without a hand-edited marker being overwritten.
    /// </summary>
    internal const string LegacyIgnoreContents = "*\n";

    /// <summary>
    ///     True when <paramref name="path" /> is inside a <c>.skala/</c> directory, at any depth.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>Every file walker in the tool needs this, and none of them had it.</b> The directory
    ///     holds <c>.cs</c> files — <c>crash/&lt;hash&gt;/input.cs</c> and <c>output.cs</c>, the
    ///     reproduction Skala writes when the formatter crashes on a file. The scan exclusions are a
    ///     hard-coded list of <c>obj</c>, <c>bin</c>, <c>.git</c> and <c>artifacts</c>; <c>.skala</c>
    ///     was not on it, and the ignore that covers those crash files is the nested <c>.gitignore</c>
    ///     this type writes, which no walker reads. So the first SK9099 on a repository made every
    ///     later run format and analyse Skala's own crash reproductions: on Vixen the file count moved
    ///     from 4 717 to 4 725 after <c>arrange</c> wrote two of them, and the findings against those
    ///     files were reported against the user's tree.
    ///     <para>
    ///         A crash reproduction must be kept byte-for-byte as it was — reformatting it destroys the
    ///         evidence it exists to preserve — so this is an exclusion rather than something the ignore
    ///         file should have been expected to handle.
    ///     </para>
    /// </remarks>
    public static bool Contains(string path) {
        var separator = Path.DirectorySeparatorChar;
        return path.Contains($"{separator}{Name}{separator}", StringComparison.Ordinal)
            || path.StartsWith($"{Name}{separator}", StringComparison.Ordinal);
    }

    /// <summary>
    ///     <c>&lt;repositoryRoot&gt;/.skala/&lt;segments&gt;</c> — computed only, nothing is created.
    /// </summary>
    public static string PathFor(string repositoryRoot, params string[] segments) =>
        Combine(Path.Combine(repositoryRoot, Name), segments);

    static string Combine(string head, string[] segments) {
        var result = head;
        foreach (var segment in segments) {
            result = Path.Combine(result, segment);
        }

        return result;
    }

    /// <summary>
    ///     Creates <c>&lt;repositoryRoot&gt;/.skala/&lt;segments&gt;</c> and guarantees the self-ignore marker.
    /// </summary>
    /// <returns>The full path of the created directory.</returns>
    public static string Ensure(string repositoryRoot, params string[] segments) {
        var skala = Path.Combine(repositoryRoot, Name);
        var target = Combine(skala, segments);
        Directory.CreateDirectory(target);
        Mark(skala);
        return target;
    }

    /// <summary>
    ///     The same, for callers that already hold the <c>.skala</c> directory rather than the
    ///     repository root — the crash-artefact path is handed one and never sees the root.
    /// </summary>
    public static string EnsureAt(string skalaDirectory, params string[] segments) {
        var target = Combine(skalaDirectory, segments);
        Directory.CreateDirectory(target);
        Mark(skalaDirectory);
        return target;
    }

    /// <summary>
    ///     Creates the directory <paramref name="filePath" /> will be written into, and marks the
    ///     nearest <c>.skala</c> above it. This is the shape every writer already had — the cache, the
    ///     clone index, the SARIF report and the daemon socket all hold a full file path and created
    ///     its parent — so adopting it is a one-line change per call site rather than a refactor.
    /// </summary>
    /// <remarks>
    ///     ⚠ When no <c>.skala</c> component is present the parent directory is still created and no
    ///     marker is written. That is the <c>--output</c> case: a report the user redirected somewhere
    ///     of their own choosing is theirs, and silently dropping a <c>.gitignore</c> beside it would
    ///     be the same discourtesy this type exists to stop.
    /// </remarks>
    public static void EnsureForFile(string filePath) {
        var parent = Path.GetDirectoryName(filePath);

        // ⚠ Empty and null are both "there is no directory to create", and only null was handled.
        // `Path.GetDirectoryName` returns null for a root and the empty string for a bare filename,
        // so `-o report.sarif` reached `Directory.CreateDirectory("")` and threw ArgumentException
        // *after the whole analysis had run* (#305). The bare filename is the spelling a person
        // reaches for first, and the file belongs in the current directory — which needs no creating.
        if (string.IsNullOrEmpty(parent)) {
            return;
        }

        Directory.CreateDirectory(parent);

        for (var directory = parent; directory is not null; directory = Path.GetDirectoryName(directory)) {
            if (string.Equals(Path.GetFileName(directory), Name, StringComparison.Ordinal)) {
                Mark(directory);
                return;
            }
        }
    }

    /// <summary>
    ///     Writes the marker if it is absent, and upgrades the pre-M9 bare <c>*</c> in place.
    ///     ⚠ Idempotent and cheap: this sits under the daemon's socket bind and under every cache
    ///     write, so the warm path is one <c>File.ReadAllText</c> of three lines. A marker the user has
    ///     edited — anything that is neither the current nor the legacy payload — is left exactly as
    ///     they left it.
    /// </summary>
    public static void Mark(string skalaDirectory) {
        try {
            var marker = Path.Combine(skalaDirectory, ".gitignore");
            if (!File.Exists(marker)) {
                File.WriteAllText(marker, IgnoreContents);
                return;
            }

            // ⚠ Only the exact legacy bytes are replaced. Matching loosely here would mean editing
            // a file somebody chose the contents of, which is the one thing this type promises not
            // to do.
            if (string.Equals(
                    File.ReadAllText(marker).ReplaceLineEndings("\n"),
                    LegacyIgnoreContents,
                    StringComparison.Ordinal
                )) {
                File.WriteAllText(marker, IgnoreContents);
            }
        } catch (IOException) {
            // A read-only tree, or a race with another process writing the same marker. Neither is
            // worth failing the caller's actual work over.
        } catch (UnauthorizedAccessException) {
            // The same answer for the same reason: a tree the process may read and not write. Marking
            // `.skala/` is housekeeping around the caller's work, never the caller's work itself.
        }
    }
}
