// <auto-generated/>
// A generator emits the signature its template holds; it is not a decision made here.
namespace Fixtures {
    abstract class GeneratedWriter {
        public virtual void Write(string text, bool flush = false) { }
    }

    sealed class GeneratedBuffered : GeneratedWriter {
        public override void Write(string text, bool flush = true) { }
    }
}
