// <auto-generated/>
// A generator emits the signature its template holds; it is not a decision made here.
using System;
using System.Threading.Tasks;

public sealed class GeneratedPanel {
    public async void Refresh() {
        await Task.Yield();
        throw new InvalidOperationException("nothing to refresh");
    }
}
