// <auto-generated/>
// A generator emits the extension shape its template holds; it is not a decision made here.
namespace Fixtures {
    static class GeneratedExtensions {
        public static bool IsBlank(this string value) => string.IsNullOrWhiteSpace(value);

        public static string Repeat(this string value, int times) => new string('x', times) + value;
    }
}
