using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Rikarin.Skala.Conformance.Sweep;

/// <summary>One pair's row, in the shape another pass can read back.</summary>
public sealed record PairRow(
    string Primary,
    string Secondary,
    string Fixture,
    string Outcome,
    int OracleDistinct,
    int SkalaDistinct,
    bool BaselineAgrees,
    IReadOnlyList<PairCorner> Corners);

/// <summary>
///     Renders the pairwise run as a committed file, reviewed in a diff like every other measurement.
/// </summary>
/// <remarks>
///     ⚠ Its own pair of files rather than more columns on the single sweep's. They answer different
///     questions, they are run on different cadences, and — the deciding reason —
///     <c>OptionCoverageTests</c> reads <c>conformance-sweep.json</c> to decide tiers. Folding a second
///     measurement into that file would put a pair's verdict where a test is looking for an option's,
///     and the tier system has already been diluted once by a claim nothing checked.
/// </remarks>
public static class PairwiseReport {
    static readonly JsonSerializerOptions Json =
        new() { WriteIndented = true, DefaultIgnoreCondition = JsonIgnoreCondition.Never };

    /// <summary>Every pair the run could not substantiate, worst first.</summary>
    /// <remarks>
    ///     ⚠ <c>InteractionOnly</c> is listed before <c>Divergent</c> deliberately. An ordinary divergence
    ///     is already owned by the single sweep's table; an interaction is a defect no other instrument in
    ///     the repository can see, so it is the row a reader should reach first.
    /// </remarks>
    public static IReadOnlyList<PairSweep> Findings(PairwiseRun run) => [
        .. run.Pairs
            .Where(static pair => !pair.IsGreen)
            .OrderBy(static pair => pair.Outcome switch {
                    PairOutcome.InteractionOnly => 0,
                    PairOutcome.Divergent => 1,
                    PairOutcome.Unexercised => 2,
                    PairOutcome.Inherited => 3,
                    PairOutcome.BaselineDivergent => 4,
                    _ => 5
                }
            )
            .ThenBy(static pair => pair.PrimaryKey, StringComparer.Ordinal)
    ];

    public static void WriteJson(string path, PairwiseRun run) =>
        File.WriteAllText(
            path,
            JsonSerializer.Serialize(
                run.Pairs
                    .OrderBy(static pair => pair.PrimaryKey, StringComparer.Ordinal)
                    .ThenBy(static pair => pair.SecondaryKey, StringComparer.Ordinal)
                    .Select(static pair => new PairRow(
                            pair.PrimaryKey,
                            pair.SecondaryKey,
                            pair.Fixture,
                            pair.Outcome.ToString(),
                            pair.OracleDistinct,
                            pair.SkalaDistinct,
                            pair.BaselineAgrees,
                            pair.Corners
                        )
                    )
                    .ToArray(),
                Json
            )
            + "\n"
        );

    public static string Render(PairwiseRun run, IReadOnlyList<string> families) {
        var builder = new StringBuilder();
        builder.AppendLine("# Pairwise conformance sweep");
        builder.AppendLine();
        builder.AppendLine("Two options at once, over the whole grid of their values, Skala against");
        builder.AppendLine("`jb cleanupcode`. Generated by `./build.sh Pairwise`; see docs/plan/12 §");
        builder.AppendLine("\"Interactions are out of scope\", which named this pass and is what it answers.");
        builder.AppendLine();
        builder.AppendLine("⚠ **`INTERACTION` is the verdict this pass exists for.** It means every corner the");
        builder.AppendLine("one-at-a-time sweep can reach agrees, and an interior corner does not — two options");
        builder.AppendLine("that are each conformant alone and wrong together. `conformance-sweep.md` reports");
        builder.AppendLine("both of them green and is not wrong to: it cannot reach the corner.");
        builder.AppendLine();
        builder.AppendLine("⚠ **`UNEXERCISED` is not a pass**, for the same reason it is not one there.");
        builder.AppendLine();
        builder.AppendLine("⚠ **`INHERITED` is not a finding about the pair either.** Every corner that");
        builder.AppendLine("disagrees does so at a value where `conformance-sweep.json` already records one of");
        builder.AppendLine("the two keys diverging on its own. 17 rows of this pass's first corrected run were");
        builder.AppendLine("this, all of them `max_line_length` at `0` and `1`.");
        builder.AppendLine();
        builder.AppendLine("⚠ **`BASELINE` is not a finding about the pair.** The two engines already disagreed");
        builder.AppendLine("on that fixture before either key was set, so its grid answers nothing — the work is");
        builder.AppendLine("in `docs/divergences.md`, not here.");
        builder.AppendLine();

        builder.AppendLine("| | |");
        builder.AppendLine("|---|---|");
        builder.AppendLine("| ReSharper | " + run.OracleVersion + " |");
        builder.AppendLine("| base configuration | the repository export, sha256 `" + run.ConfigDigest + "` |");
        builder.AppendLine("| families | " + (families.Count == 0 ? "all" : string.Join(", ", families)) + " |");
        builder.AppendLine("| pairs swept | " + Count(run.Pairs.Count) + " |");
        builder.AppendLine("| corners | " + Count(run.Pairs.Sum(static pair => pair.Corners.Count)) + " |");
        builder.AppendLine("| rounds | " + Count(run.Rounds) + " (batched by corner index) |");
        builder.AppendLine("| `cleanupcode` invocations | " + Count(run.OracleInvocations) + " |");
        builder.AppendLine("| oracle wall clock | " + Duration(run.OracleWallClock) + " |");
        builder.AppendLine("| Skala wall clock | " + Duration(run.SkalaWallClock) + " |");
        builder.AppendLine();

        if (run.BrokenRounds.Count > 0) {
            builder.AppendLine("## ⚠ Broken measurements");
            builder.AppendLine();
            builder.AppendLine(
                "**" + Count(run.BrokenRounds.Count) + " of this run's canaries fired.** Everything below is"
            );
            builder.AppendLine("suspect until somebody has looked.");
            builder.AppendLine();
            builder.AppendLine("| round | population | answered | moved | what fired |");
            builder.AppendLine("|---|---:|---:|---:|---|");
            foreach (var fired in run.BrokenRounds) {
                builder.AppendLine(
                    "| "
                    + (fired.Round is { } index ? Count(index + 1) : "baseline")
                    + " | "
                    + Count(fired.Population)
                    + " | "
                    + Count(fired.Answered)
                    + " | "
                    + Count(fired.Moved)
                    + " | "
                    + fired.Reason
                    + " |"
                );
            }

            builder.AppendLine();
        }

        builder.AppendLine("## Outcomes");
        builder.AppendLine();
        builder.AppendLine("| outcome | pairs | meaning |");
        builder.AppendLine("|---|---:|---|");
        foreach (var outcome in Enum.GetValues<PairOutcome>()) {
            builder.AppendLine(
                "| "
                + Label(outcome)
                + " | "
                + Count(run.Pairs.Count(pair => pair.Outcome == outcome))
                + " | "
                + Meaning(outcome)
                + " |"
            );
        }

        builder.AppendLine();

        var findings = Findings(run);
        builder.AppendLine("## Findings");
        builder.AppendLine();
        if (findings.Count == 0) {
            builder.AppendLine("None. Every pair agrees at every corner of its grid.");
            builder.AppendLine();
        } else {
            builder.AppendLine("| pair | outcome | corners | agreeing | the corners that disagree |");
            builder.AppendLine("|---|---|---:|---:|---|");
            foreach (var pair in findings) {
                var disagreeing = pair.Corners.Where(static corner => !corner.Agree)
                    .Select(static corner => "`" + corner.PrimaryValue + "` × `" + corner.SecondaryValue + "`")
                    .Take(4);
                builder.AppendLine(
                    "| `"
                    + pair.PrimaryKey
                    + "` × `"
                    + pair.SecondaryKey
                    + "` | "
                    + Label(pair.Outcome)
                    + " | "
                    + Count(pair.Corners.Count)
                    + " | "
                    + Count(pair.Agreements)
                    + " | "
                    + string.Join(", ", disagreeing)
                    + " |"
                );
            }

            builder.AppendLine();
        }

        builder.AppendLine("## Per pair");
        builder.AppendLine();
        builder.AppendLine("`reach` counts the corners the one-at-a-time sweep also visits — the row and the");
        builder.AppendLine("column through the export's own values. A pair whose only disagreements are outside");
        builder.AppendLine("that cross is an interaction and nothing else in the repository can see it.");
        builder.AppendLine();
        builder.AppendLine("| primary | secondary | outcome | corners | agree | reach | oracle | skala | base | fixture |");
        builder.AppendLine("|---|---|---|---:|---:|---:|---:|---:|---|---|");
        foreach (var pair in run.Pairs.OrderBy(static pair => pair.PrimaryKey, StringComparer.Ordinal)) {
            builder.AppendLine(
                "| `"
                + pair.PrimaryKey
                + "` | `"
                + pair.SecondaryKey
                + "` | "
                + Label(pair.Outcome)
                + " | "
                + Count(pair.Corners.Count)
                + " | "
                + Count(pair.Agreements)
                + " | "
                + Count(pair.Corners.Count(static corner => corner.ReachedBySingleSweep))
                + " | "
                + Count(pair.OracleDistinct)
                + " | "
                + Count(pair.SkalaDistinct)
                + " | "
                + (pair.BaselineAgrees ? "=" : "⚠")
                + " | `"
                + pair.Fixture
                + "` |"
            );
        }

        builder.AppendLine();

        if (run.Excluded.Count > 0) {
            builder.AppendLine("## Not swept");
            builder.AppendLine();
            builder.AppendLine("| pairs | reason |");
            builder.AppendLine("|---:|---|");
            foreach (var group in run.Excluded
                         .GroupBy(static exclusion => exclusion.Reason, StringComparer.Ordinal)
                         .OrderByDescending(static group => group.Count())) {
                builder.AppendLine("| " + Count(group.Count()) + " | " + group.Key + " |");
            }

            builder.AppendLine();
        }

        return builder.ToString();
    }

    static string Label(PairOutcome outcome) =>
        outcome switch {
            PairOutcome.Conformant => "✅ CONFORMANT",
            PairOutcome.InteractionOnly => "⚠ INTERACTION",
            PairOutcome.Divergent => "❌ DIVERGENT",
            PairOutcome.Unexercised => "⚠ UNEXERCISED",
            PairOutcome.Inherited => "⚠ INHERITED",
            PairOutcome.BaselineDivergent => "⚠ BASELINE",
            _ => "⚠ NO FIXTURE"
        };

    static string Meaning(PairOutcome outcome) =>
        outcome switch {
            PairOutcome.Conformant => "every corner of the grid agrees",
            PairOutcome.InteractionOnly =>
                "**every corner the single sweep reaches agrees, and an interior corner does not**",
            PairOutcome.Divergent => "a corner disagrees, and the single sweep could have seen it too",
            PairOutcome.Unexercised => "**neither engine distinguished the corners.** Not a pass",
            PairOutcome.Inherited =>
                "⚠ every disagreement is one the single sweep already records for one of the two keys, "
                + "measured alone — not a finding about the pair",
            PairOutcome.BaselineDivergent =>
                "⚠ the two engines already disagreed on this fixture before either key was set, so the "
                + "grid cannot report on the pair",
            _ => "the pair names no fixture the corpus has"
        };

    static string Count(int value) => value.ToString(CultureInfo.InvariantCulture);

    static string Duration(TimeSpan span) =>
        span.TotalSeconds < 90
            ? span.TotalSeconds.ToString("0.0", CultureInfo.InvariantCulture) + " s"
            : span.TotalMinutes.ToString("0.0", CultureInfo.InvariantCulture) + " min";
}
