using Rikarin.Skala.Options;
using System.Globalization;
using System.Text;

namespace Rikarin.Skala.Conformance.Sweep;

/// <summary>A Tier A claim the sweep could not substantiate, and the reason to record with it.</summary>
public sealed record Demotion(string Key, SweepOutcome Outcome, string Fixture, string Reason);

/// <summary>
///     Renders the sweep's result as a file that is reviewed in a diff, the way the oracle fixtures are.
/// </summary>
/// <remarks>
///     ⚠ The table is committed on purpose. The sweep needs JetBrains installed and takes minutes, so it
///     is a nightly job and never a commit gate (ADR-011: the oracle is a developer-machine and nightly
///     dependency, never a runtime one). What the fast path gets is this file, and what makes a
///     regression visible is its diff — an option that was <c>Conformant</c> yesterday and is
///     <c>Unexercised</c> today is one line in a pull request rather than a number nobody re-derived.
/// </remarks>
public static class SweepReport {
    /// <summary>
    ///     Every Tier A option the sweep could not substantiate.
    /// </summary>
    /// <remarks>
    ///     ⚠ Tier A means "Skala reproduces Rider's behaviour, pinned by at least one oracle fixture"
    ///     (docs/plan/03 § "Four tiers"). An option whose fixture cannot tell its values apart is pinned
    ///     by nothing: the fixture would be byte-identical whatever the option said, so it is evidence
    ///     that the option was not read rather than evidence that it was honoured. M3.1 found options
    ///     marked Tier A that could not be observed at all, and every one of them is a dilution of the
    ///     tier system. They are demoted with the reason recorded, not explained away.
    /// </remarks>
    public static IReadOnlyList<Demotion> TierAudit(SweepRun run) => [
        .. run.Options
            .Where(static option => option.Tier == OptionTier.A && option.Outcome != SweepOutcome.Conformant)
            .Select(static option => new Demotion(option.Key, option.Outcome, option.Fixture, Reason(option)))
            .OrderBy(static demotion => demotion.Key, StringComparer.Ordinal)
    ];

    static string Reason(OptionSweep option) =>
        option.Outcome switch {
            SweepOutcome.Unexercised =>
                "neither engine's output moved across "
                + Count(option.Values.Count)
                + " values, so the fixture pins nothing",
            SweepOutcome.Inert =>
                "the oracle produced "
                + Count(option.OracleDistinct)
                + " distinct outputs and Skala one: ReSharper honours the key and Skala does not",
            SweepOutcome.Spurious =>
                "Skala produced "
                + Count(option.SkalaDistinct)
                + " distinct outputs and the oracle one: Skala reacts where ReSharper does not",
            SweepOutcome.Divergent =>
                "outputs disagree at "
                + Count(option.Values.Count - option.Agreements)
                + " of "
                + Count(option.Values.Count)
                + " values"
                + (option.BaselineAgrees ? "" : " (the fixture already diverged at the base configuration)"),
            SweepOutcome.NoFixture => "no corpus fixture",
            _ => "conformant"
        };

    public static string Render(SweepRun run, IReadOnlyList<string> families) {
        var builder = new StringBuilder();
        builder.AppendLine("# Key-flip conformance sweep");
        builder.AppendLine();
        builder.AppendLine("Every option, at every legal value, formatted by Skala and by `jb cleanupcode` under the");
        builder.AppendLine(
            "same configuration. Generated by `./build.sh Sweep`; see docs/plan/12 § \"The key-flip sweep\"."
        );
        builder.AppendLine();
        builder.AppendLine("⚠ **`UNEXERCISED` is not a pass.** It says the fixture could not tell the option's");
        builder.AppendLine("values apart — either the fixture is too weak or the option is inert. Reading it as");
        builder.AppendLine("green rebuilds the exact defect this harness exists to detect.");
        builder.AppendLine();

        builder.AppendLine("| | |");
        builder.AppendLine("|---|---|");
        builder.AppendLine("| ReSharper | " + run.OracleVersion + " |");
        builder.AppendLine("| base configuration | the repository export, sha256 `" + run.ConfigDigest + "` |");
        builder.AppendLine("| families | " + (families.Count == 0 ? "all" : string.Join(", ", families)) + " |");
        builder.AppendLine("| options swept | " + Count(run.Options.Count) + " |");
        builder.AppendLine("| configurations | " + Count(run.Options.Sum(static option => option.Values.Count)) + " |");
        builder.AppendLine(
            "| rounds | "
            + Count(run.Rounds)
            + " (batched by value index, at most "
            + Count(KeyFlipSweep.BatchSize)
            + " fixtures per invocation — and each fixture at most once under the cleanup profile, "
            + "which resolves symbols) |"
        );
        builder.AppendLine("| `cleanupcode` invocations | " + Count(run.OracleInvocations) + " |");
        builder.AppendLine("| oracle wall clock | " + Duration(run.OracleWallClock) + " |");
        builder.AppendLine("| Skala wall clock | " + Duration(run.SkalaWallClock) + " |");
        builder.AppendLine(
            "| oracle cost per option | "
            + Duration(run.Options.Count == 0 ? TimeSpan.Zero : run.OracleWallClock / run.Options.Count)
            + " (the whole run, baseline included, over the options swept) |"
        );
        builder.AppendLine();

        // ⚠ Before the outcomes, not after them. A fired canary says the numbers below it may be
        // fiction, and a caveat printed under the table it qualifies is a caveat read second.
        if (run.BrokenRounds.Count > 0) {
            builder.AppendLine("## ⚠ Broken measurements");
            builder.AppendLine();
            builder.AppendLine(
                "**"
                + Count(run.BrokenRounds.Count)
                + " of this run's canaries fired.** A canary here does not say an option is wrong — it says"
            );
            builder.AppendLine("the instrument may not have been running, and that everything below is suspect until");
            builder.AppendLine("somebody has looked. Confirm one with `sweep verify <key>`, which re-asks a");
            builder.AppendLine("single option unbatched and prints both engines' output at every value.");
            builder.AppendLine();
            builder.AppendLine("| round | population | answered | moved | what fired |");
            builder.AppendLine("|---|---:|---:|---:|---|");
            foreach (var fired in run.BrokenRounds) {
                builder.Append("| ")
                    .Append(fired.Round is { } index ? Count(index + 1) : "baseline")
                    .Append(" | ")
                    .Append(Count(fired.Population))
                    .Append(" | ")
                    .Append(Count(fired.Answered))
                    .Append(" | ")
                    .Append(Count(fired.Moved))
                    .Append(" | ")
                    .Append(fired.Reason)
                    .AppendLine(" |");
            }

            builder.AppendLine();
        }

        builder.AppendLine("## Outcomes");
        builder.AppendLine();
        builder.AppendLine("| outcome | options | meaning |");
        builder.AppendLine("|---|---:|---|");
        foreach (var outcome in Enum.GetValues<SweepOutcome>()) {
            var count = run.Options.Count(option => option.Outcome == outcome);
            builder.Append("| ")
                .Append(Label(outcome))
                .Append(" | ")
                .Append(Count(count))
                .Append(" | ")
                .Append(Meaning(outcome))
                .AppendLine(" |");
        }

        builder.AppendLine();

        var audit = TierAudit(run);
        builder.AppendLine("## Tier audit");
        builder.AppendLine();
        builder.AppendLine(
            "Tier A options the sweep could not substantiate: **"
            + Count(audit.Count)
            + "**"
            + " of "
            + Count(run.Options.Count(static option => option.Tier == OptionTier.A))
            + " swept. Each is a dilution of the tier system and must be demoted."
        );
        builder.AppendLine();
        if (audit.Count == 0) {
            builder.AppendLine("None.");
        } else {
            builder.AppendLine("| option | outcome | fixture | reason |");
            builder.AppendLine("|---|---|---|---|");
            foreach (var demotion in audit) {
                builder.Append("| `")
                    .Append(demotion.Key)
                    .Append("` | ")
                    .Append(Label(demotion.Outcome))
                    .Append(" | `")
                    .Append(demotion.Fixture)
                    .Append("` | ")
                    .Append(demotion.Reason)
                    .AppendLine(" |");
            }
        }

        builder.AppendLine();
        builder.AppendLine("## Per option");
        builder.AppendLine();
        builder.AppendLine("`oracle` and `skala` are the number of distinct outputs each engine produced across the");
        builder.AppendLine("option's values; `agree` is how many of those values the two agreed on, after the");
        builder.AppendLine("line-ending normalisation every measurement in this repository uses.");
        builder.AppendLine("`base` is whether the two already agreed on the fixture before the key was touched,");
        builder.AppendLine("and `ms` is the option's share of the rounds it appeared in — the baseline is not");
        builder.AppendLine("attributed to any option, so these sum to less than the wall clock above.");
        builder.AppendLine();
        builder.AppendLine("⚠ `raw` marks an option whose verdict had to be read off the raw bytes because");
        builder.AppendLine("line-ending normalisation erased its entire effect. Only the line-terminator and");
        builder.AppendLine("final-newline options are in that position, and a normalised comparison reports");
        builder.AppendLine("them `UNEXERCISED` for a reason that is about the instrument, not the option.");
        builder.AppendLine();
        builder.AppendLine("| option | tier | outcome | values | oracle | skala | agree | base | raw | ms | fixture |");
        builder.AppendLine("|---|---|---|---:|---:|---:|---:|---|---|---:|---|");

        foreach (var option in run.Options
                     .OrderBy(static option => option.Outcome)
                     .ThenBy(static option => option.Key, StringComparer.Ordinal)) {
            builder.Append("| `")
                .Append(option.Key)
                .Append("` | ")
                .Append(option.Tier.ToString())
                .Append(" | ")
                .Append(Label(option.Outcome))
                .Append(" | ")
                .Append(Count(option.Values.Count))
                .Append(" | ")
                .Append(Count(option.OracleDistinct))
                .Append(" | ")
                .Append(Count(option.SkalaDistinct))
                .Append(" | ")
                .Append(Count(option.Agreements))
                .Append(" | ")
                .Append(option.BaselineAgrees ? "=" : "≠")
                .Append(" | ")
                .Append(option.LineEndingOnly ? "raw" : "")
                .Append(" | ")
                .Append(option.Cost.TotalMilliseconds.ToString("F0", CultureInfo.InvariantCulture))
                .Append(" | `")
                .Append(option.Fixture)
                .AppendLine("` |");
        }

        if (run.Excluded.Count > 0) {
            builder.AppendLine();
            builder.AppendLine("## Not swept");
            builder.AppendLine();
            builder.AppendLine(
                "⚠ These are not passes either. An option with no fixture has nothing pinning it, which"
            );
            builder.AppendLine("is the same hole `UNEXERCISED` names, reached one step earlier.");
            builder.AppendLine();
            builder.AppendLine("| reason | options | by tier |");
            builder.AppendLine("|---|---:|---|");
            foreach (var group in run.Excluded
                         .GroupBy(static exclusion => exclusion.Reason, StringComparer.Ordinal)
                         .OrderByDescending(static group => group.Count())) {
                // ⚠ Broken down by tier rather than left as one number. `resharper_int_align` — the
                // key whose two values produce byte-identical output and which no test noticed — is
                // in the largest of these buckets, and a bare count is exactly the shape in which it
                // stayed invisible.
                var tiers = group.GroupBy(static exclusion => exclusion.Info.Tier)
                    .OrderBy(static tier => tier.Key)
                    .Select(static tier => tier.Key + ": " + Count(tier.Count()));
                builder.Append("| ")
                    .Append(group.Key)
                    .Append(" | ")
                    .Append(Count(group.Count()))
                    .Append(" | ")
                    .Append(string.Join(", ", tiers))
                    .AppendLine(" |");
            }

            // ⚠ The arrangement rows are deliberately not counted here. They claim Tier A and they
            // are entitled to: `OptionCoverageTests` measures them against the arranger, and
            // `ArrangementOptionTests` records a hand-checked flipped-value reading for each.
            // What this call-out is for is a Tier A claim with *no* evidence behind it, which is a
            // different and worse thing than one this profile cannot see.
            //
            // ⚠ The set this excuses is now nearly empty, and that is the point: the 44 arrangement
            // keys are swept under `OracleProfile.Cleanup` and appear in the table above with real
            // verdicts. Only a key whose `oracle` glob names a fixture outside
            // `constructs/arrangement/` still lands here — for that key the format-only reasoning
            // still holds exactly.
            var unevidenced = run.Excluded
                .Where(static exclusion => exclusion.Info.Tier == OptionTier.A
                    && !exclusion.Reason.StartsWith("arrangement option", StringComparison.Ordinal)
                )
                .ToArray();
            if (unevidenced.Length > 0) {
                builder.AppendLine();
                builder.AppendLine(
                    "⚠ Of those, **"
                    + Count(unevidenced.Length)
                    + "** claim Tier A with nothing this sweep can reach: "
                    + string.Join(
                        ", ",
                        unevidenced.Select(static e => "`" + e.Info.Key + "`").Order(StringComparer.Ordinal)
                    )
                );
            }
        }

        return builder.ToString();
    }

    static string Label(SweepOutcome outcome) =>
        outcome switch {
            SweepOutcome.Conformant => "✅ CONFORMANT",
            SweepOutcome.Divergent => "❌ DIVERGENT",
            SweepOutcome.Inert => "❌ INERT",
            SweepOutcome.Spurious => "❌ SPURIOUS",
            SweepOutcome.Unexercised => "⚠ UNEXERCISED",
            _ => "⚠ NO FIXTURE"
        };

    static string Meaning(SweepOutcome outcome) =>
        outcome switch {
            SweepOutcome.Conformant => "both engines moved and every value's output agrees",
            SweepOutcome.Divergent => "both engines moved and at least one value's output disagrees",
            SweepOutcome.Inert => "the oracle moved and Skala did not — the key is ignored",
            SweepOutcome.Spurious => "Skala moved and the oracle did not",
            SweepOutcome.Unexercised => "**neither moved.** The fixture does not exercise the option, or it is inert",
            _ => "the registry names no fixture the corpus has"
        };

    static string Duration(TimeSpan value) =>
        value.TotalSeconds < 1
        ? value.TotalMilliseconds.ToString("F0", CultureInfo.InvariantCulture) + " ms"
        : value.TotalSeconds < 90
            ? value.TotalSeconds.ToString("F1", CultureInfo.InvariantCulture) + " s"
            : value.TotalMinutes.ToString("F1", CultureInfo.InvariantCulture) + " min";

    static string Count(int value) => value.ToString(CultureInfo.InvariantCulture);
}
