// <auto-generated/>
// A generator writes the template and the argument list together; the names it repeats are the
// generator's decision and not one anybody in this repository can act on.
namespace Serilog {
    interface ILogger {
        void Information(string messageTemplate, params object[] propertyValues);
    }
}

namespace Fixtures {
    sealed class GeneratedWorker {
        public void Run(Serilog.ILogger logger, string from, string to) {
            logger.Information("Moved {Path} to {Path}", from, to);
        }
    }
}
