// <auto-generated/>
// A generator emits the constructor form its template holds; it is not a decision made here.
namespace Fixtures {
    sealed class GeneratedRetry(int attempts) {
        public bool Next() {
            attempts--;
            return attempts > 0;
        }
    }
}
