<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rikarin.Skala.Formatting.CSharp</RootNamespace>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Rikarin.Skala.Formatting/Rikarin.Skala.Formatting.csproj" />
    <ProjectReference Include="../../Core/Rikarin.Skala.Core/Rikarin.Skala.Core.csproj" />
  </ItemGroup>
</Project>
