using Rikarin.Skala.Testing;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Rikarin.Skala.Conformance.Tests;

/// <summary>
///     Every committed measurement is a measurement of the configuration that is still on disk.
/// </summary>
/// <remarks>
///     ⚠ <b>The hole this closes.</b> Each oracle fixture carries a provenance header naming the
///     ReSharper version and the digest of the base <c>.editorconfig</c> it was generated under, and
///     until this file existed <em>nothing in the repository read it</em>. The consequence is not
///     hypothetical and it is not detectable by any other test here: the whole suite compares Skala's
///     output against frozen fixtures, so when the base configuration changes, both sides of every
///     comparison stay exactly where they were and the suite stays green while every fixture in the
///     corpus silently becomes a record of a configuration that no longer exists.
///     <para>
///         It happened. At <c>076fde6</c> the base configuration was stripped of ~1 997 keys by hand and
///         its digest moved from <c>98ff5257</c> to <c>bd9791d3</c>; the corpus and the committed sweep
///         report both still said <c>98ff5257</c>, and the build was green. What follows is the instrument
///         that would have said so on the first run after that commit.
///     </para>
///     <para>
///         ⚠ These tests deliberately do <b>not</b> regenerate anything. An oracle that refreshes itself
///         when it disagrees is a tautology (docs/plan/12 § "The oracle"), and that argument applies with
///         more force to provenance than to content: a header that re-stamps itself records nothing at
///         all. Both failures below say what to run and leave the running to a person.
///     </para>
/// </remarks>
public sealed class ProvenanceTests {
    /// <summary>How many offending fixtures to name before falling back to a count.</summary>
    /// <remarks>
    ///     ⚠ There are ~2 000 fixtures and the realistic failure moves all of them at once, so the
    ///     message has to be a summary rather than a listing. A test whose output is two thousand lines
    ///     is a test nobody reads to the end of, and the count is the part that says what happened.
    /// </remarks>
    const int Examples = 5;

    /// <summary>
    ///     The number of <c>corpus/real</c> sources every published sweep in docs/plan/08 was measured
    ///     over — the originals, with the two oracle twins of each left behind.
    /// </summary>
    const int SweptSources = 380;

    /// <summary>
    ///     The per-vendored-tree split of <see cref="SweptSources" />, as docs/plan/08 attributes its
    ///     findings.
    /// </summary>
    static readonly (string Tree, int Sources)[] Trees = [("newtonsoft", 110), ("serilog", 70), ("vixen", 200)];

    /// <summary>
    ///     The file the oracle is handed is the Rider export, and not the repository's own
    ///     configuration.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>The hole this closes, and it is a different shape from the two below.</b> Those catch a
    ///     configuration that <em>changed</em>; this catches a configuration that was never read. Until
    ///     <c>OracleEditorConfig</c> the harness copied <c>&lt;root&gt;/.editorconfig</c> into its
    ///     scratch project, which worked only because that file was byte-identical to
    ///     <c>editor_config_template</c> with <c>root = true</c> prepended. The repository's own file
    ///     answers to ADR-015 and is free to change spelling; <c>cleanupcode</c> does not report a key
    ///     it cannot read, it ignores it. So the failure would be a full corpus regenerated by an
    ///     oracle running on its own built-in defaults — every fixture plausible, every digest test
    ///     green, and the provenance header recording the digest of a file that configured nothing.
    ///     <para>
    ///         ⚠ The digest is unchanged by the separation and that is the check, not a coincidence:
    ///         the oracle's bytes were always the export's bytes, so
    ///         <see cref="EveryFixture_RecordsTheConfigurationInForce" /> continues to hold every
    ///         committed fixture to the same <c>sha256</c> it held them to before.
    ///     </para>
    /// </remarks>
    [Fact]
    public void TheOracleIsConfiguredByTheExport() {
        var handed = File.ReadAllBytes(Corpus.OracleEditorConfigPath);
        var template = File.ReadAllBytes(OracleEditorConfig.TemplatePath);
        var prefix = Encoding.UTF8.GetBytes(OracleEditorConfig.RootDeclaration);

        Assert.True(
            handed.AsSpan().SequenceEqual([.. prefix, .. template]),
            Corpus.OracleEditorConfigPath
            + " is not "
            + OracleEditorConfig.TemplatePath
            + " with `root = true` prepended, so the corpus would be measured against a configuration "
            + "nobody exported."
        );

        var text = Encoding.UTF8.GetString(handed);
        Assert.StartsWith("root = true", text, StringComparison.Ordinal);
        Assert.EndsWith(Encoding.UTF8.GetString(template), text, StringComparison.Ordinal);

        // ⚠ And it is a different file from the one Skala formats Skala with. This is the assertion
        // that survives the day the two stop holding the same bytes.
        Assert.NotEqual(
            Path.GetFullPath(Corpus.RepositoryEditorConfigPath),
            Path.GetFullPath(Corpus.OracleEditorConfigPath)
        );

        var refused = Assert.Throws<InvalidOperationException>(
            static () => OracleEditorConfig.Reading(Corpus.RepositoryEditorConfigPath)
        );

        Assert.Contains("cleanupcode", refused.Message, StringComparison.Ordinal);
    }

    /// <summary>
    ///     The oracle's configuration is spelled in a key namespace ReSharper reads.
    /// </summary>
    /// <remarks>
    ///     ⚠ Free today and load-bearing the moment the repository's own configuration is renamed into
    ///     Skala's own namespace: <c>skala_*</c> is exactly the spelling <c>cleanupcode</c> would drop
    ///     on the floor in silence, so a single <c>skala_</c> assignment in the file handed to the
    ///     oracle means the oracle was handed the wrong file.
    /// </remarks>
    [Fact]
    public void TheOracleConfiguration_CarriesNoKeyReSharperCannotRead() {
        var assignments = File.ReadAllLines(Corpus.OracleEditorConfigPath)
            .Select(static line => line.Trim())
            .Where(static line => line.Length > 0
                && !line.StartsWith('#')
                && !line.StartsWith('[')
                && line.Contains('=', StringComparison.Ordinal)
            )
            .Select(static line => line[..line.IndexOf('=', StringComparison.Ordinal)].Trim())
            .ToArray();

        // The population canary: an empty file would satisfy the claim below for the wrong reason.
        Assert.True(
            assignments.Length > 0,
            Corpus.OracleEditorConfigPath + " assigns nothing. That is a broken read, not a clean export."
        );

        var alien = assignments
            .Where(static key => key.StartsWith("skala_", StringComparison.Ordinal))
            .Distinct(StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            alien.Length == 0,
            Count(alien.Length)
            + " keys in "
            + Corpus.OracleEditorConfigPath
            + " are in Skala's own namespace, which `jb cleanupcode` ignores without a word:\n"
            + Sample(alien)
            + "\n\nThe oracle reads the Rider export. See OracleEditorConfig."
        );
    }

    /// <summary>
    ///     Every fixture records the digest of the base configuration as it stands on disk.
    /// </summary>
    /// <remarks>
    ///     ⚠ A fixture with no header is a failure and not a skip. "Missing means nobody measured" is
    ///     the standing convention here — <c>OptionCoverageTests.SweepUnsubstantiated</c> makes the same
    ///     move for a missing sweep report, returning empty so that the strict invariant is *restored*
    ///     rather than quietly relaxed. A header-less fixture is a file claiming to be an oracle
    ///     measurement while declining to say what it measured, which is the weaker of the two states
    ///     this test exists to reject.
    /// </remarks>
    [Fact]
    public void EveryFixture_RecordsTheConfigurationInForce() {
        var fixtures = Corpus.Fixtures();

        // ⚠ The population canary, in the shape KeyFlipSweep.IsBrokenMeasurement names: a test that
        // asserts something of every member of an empty set passes for the one reason that means it
        // measured nothing. The corpus is ~2 000 fixtures; zero is a broken enumeration.
        Assert.True(
            fixtures.Count > 0,
            $"no `*.expected.cs` found under {Corpus.Root}. That is a broken enumeration, not a clean corpus."
        );

        var inForce = OracleFixture.ConfigDigestInForce();
        var headerless = new List<string>();
        var mismatched = new List<(string Path, string Recorded)>();

        foreach (var fixture in fixtures) {
            var header = HeaderOf(fixture);
            if (header is null) {
                headerless.Add(fixture);
                continue;
            }

            if (!string.Equals(header.ConfigHash, inForce, StringComparison.Ordinal)) {
                mismatched.Add((fixture, header.ConfigHash));
            }
        }

        Assert.True(
            headerless.Count == 0,
            Count(headerless.Count)
            + " of "
            + Count(fixtures.Count)
            + " committed fixtures carry no `"
            + OracleHeader.Prefix
            + "` header, so what they measured is unrecorded:\n"
            + Sample(headerless.Select(Relative))
            + "\n\nRegenerate them with `./build.sh Oracle`, which stamps the header as it writes."
        );

        Assert.True(
            mismatched.Count == 0,
            Count(mismatched.Count)
            + " of "
            + Count(fixtures.Count)
            + " committed fixtures were generated under a base configuration that is no longer in force.\n\n"
            + "  "
            + Corpus.OracleEditorConfigPath
            + "\n  on disk now: sha256:"
            + inForce
            + "\n"
            + Sample(mismatched.Select(static entry => Relative(entry.Path) + " records sha256:" + entry.Recorded))
            + "\n\nThe fixtures are frozen and so is Skala's side of every comparison, so this cannot "
            + "surface as a content failure — it surfaces only here.\n"
            + "Either restore the configuration, or regenerate the corpus with `./build.sh Oracle` in a "
            + "reviewed commit of its own."
        );
    }

    /// <summary>
    ///     One ReSharper version across the whole corpus.
    /// </summary>
    /// <remarks>
    ///     ⚠ Fixtures from two ReSharper versions are not comparable, and nothing else notices. The
    ///     fidelity number is a count over the whole corpus; half-regenerating it after a JetBrains
    ///     upgrade produces a corpus that is internally inconsistent and a number that is an average of
    ///     two different oracles. Any divergence class read off it afterwards is attributed to Skala
    ///     when the cause was the tool moving underneath.
    ///     <para>
    ///         The assertion is uniformity rather than a pinned version string. Upgrading the oracle is a
    ///         legitimate, deliberate act; doing half of it is not.
    ///     </para>
    /// </remarks>
    [Fact]
    public void EveryFixture_RecordsTheSameReSharperVersion() {
        var fixtures = Corpus.Fixtures();
        Assert.True(fixtures.Count > 0, $"no `*.expected.cs` found under {Corpus.Root}.");

        var byVersion = new SortedDictionary<string, List<string>>(StringComparer.Ordinal);
        foreach (var fixture in fixtures) {
            var version = HeaderOf(fixture)?.ReSharperVersion ?? "(no header)";
            if (!byVersion.TryGetValue(version, out var files)) {
                byVersion[version] = files = [];
            }

            files.Add(fixture);
        }

        Assert.True(
            byVersion.Count == 1,
            "the corpus was generated by "
            + Count(byVersion.Count)
            + " different ReSharper versions, and fixtures from two versions are not comparable:\n"
            + string.Join(
                "\n",
                byVersion.Select(static entry =>
                    "  resharper="
                    + entry.Key
                    + ": "
                    + Count(entry.Value.Count)
                    + " fixtures, e.g. "
                    + Relative(entry.Value[0])
                )
            )
            + "\n\nRegenerate the whole corpus under one version with `./build.sh Oracle`."
        );
    }

    /// <summary>
    ///     The committed key-flip sweep measured the configuration that is still on disk.
    /// </summary>
    /// <remarks>
    ///     ⚠ The sweep's table is load-bearing rather than informational.
    ///     <c>OptionCoverageTests.TierA_IsWhatSkalaReads_AndTheSweepSubstantiates</c> and
    ///     <c>TierD_CarriesAFixtureOnlyWhereTheSweepDemotedIt</c> both read
    ///     <c>conformance-sweep.json</c> and let it decide which tier an option is entitled to. A sweep
    ///     run against a configuration that has since changed is therefore not a stale note in a report:
    ///     it is the evidence two live invariants are resting on.
    ///     <para>
    ///         ⚠ The digest is read out of the <c>.md</c> because that is the only one of the pair that
    ///         records it — the <c>.json</c>, which is the file the tests actually read, carries no
    ///         provenance at all. That asymmetry is why the two files are asserted to travel together
    ///         below: the machine-readable half cannot be trusted further than the human-readable half's
    ///         header.
    ///     </para>
    ///     <para>
    ///         ⚠ A missing report is not a pass here, in the same sense that it is not a pass in
    ///         <c>SweepUnsubstantiated</c>. There it returns empty and *restores* the strict tier
    ///         invariant; here there is simply nothing that claims to have been measured, so there is
    ///         nothing to catch out. What must never be tolerated is the state in between — a
    ///         <c>.json</c> the tier tests believe with no <c>.md</c> beside it to say what it was
    ///         measured against.
    ///     </para>
    /// </remarks>
    [Fact]
    public void TheCommittedSweep_WasMeasuredAgainstTheConfigurationInForce() {
        var directory = Path.Combine(Corpus.RepositoryRoot, "Testing", "Rikarin.Skala.Conformance.Sweep");
        var json = Path.Combine(directory, "conformance-sweep.json");
        var markdown = Path.Combine(directory, "conformance-sweep.md");

        if (!File.Exists(json) && !File.Exists(markdown)) {
            return;
        }

        Assert.True(
            File.Exists(markdown),
            "conformance-sweep.json is committed and the tier tests read it, but conformance-sweep.md is "
            + "not there — and the .md is the only half of the pair that records which base configuration "
            + "the run measured. Re-run ./build.sh Sweep, which writes both."
        );

        var recorded = Regex.Match(
            File.ReadAllText(markdown),
            @"base configuration \|[^|]*sha256 `(?<digest>[0-9a-f]+)`"
        );

        Assert.True(
            recorded.Success,
            markdown
            + " records no base-configuration digest, so what it measured is unrecorded. Re-run "
            + "./build.sh Sweep."
        );

        var inForce = OracleFixture.ConfigDigestInForce();
        Assert.True(
            string.Equals(recorded.Groups["digest"].Value, inForce, StringComparison.Ordinal),
            "the sweep was measured against a configuration that is no longer in force; re-run "
            + "./build.sh Sweep.\n\n"
            + "  "
            + Corpus.OracleEditorConfigPath
            + "\n  on disk now:      sha256:"
            + inForce
            + "\n  the sweep records: sha256:"
            + recorded.Groups["digest"].Value
            + "\n\nUntil it is re-run, `OptionCoverageTests` is deciding tiers from measurements of a "
            + "configuration nobody is using."
        );
    }

    /// <summary>
    ///     The committed key-flip sweep measured the formatter that is still on disk.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>The hole this closes, and it is the twin of the one at the top of this file.</b>
    ///     <see cref="TheCommittedSweep_WasMeasuredAgainstTheConfigurationInForce" /> checks that the
    ///     sweep measured the <em>configuration</em> in force. Nothing checked that it measured the
    ///     <em>formatter</em> in force — and the sweep's table is what <c>OptionCoverageTests</c> reads
    ///     to decide which tier an option is entitled to. Between the run at <c>2a14dee</c> and the one
    ///     at <c>603fbd3</c> the tree moved 88 commits, the digest test stayed green throughout because
    ///     the <c>.editorconfig</c> had not changed, and every tier decision in that window rested on a
    ///     measurement of a formatter nobody had compared them to.
    ///     <para>
    ///         ⚠ <b>Why this can run on every commit when the sweep cannot.</b> The oracle half needs
    ///         JetBrains and minutes of wall clock, which ADR-011 forbids on the fast path. Skala's half is
    ///         485 ms for the whole run, so the archive records Skala's own output at every configuration
    ///         the sweep measured, and this re-asks it. A row that still matches means the verdict beside it
    ///         is a verdict about this formatter. A row that does not means the verdict is about a formatter
    ///         that no longer exists — which does not make the verdict wrong, only unowned.
    ///     </para>
    ///     <para>
    ///         ⚠ <b>The cost, stated rather than discovered.</b> This turns "I changed how a swept construct
    ///         formats" into a red suite until the sweep is re-run, which is 3.5 minutes and a JetBrains
    ///         install. That is deliberate and it is the same bargain
    ///         <see cref="EveryFixture_RecordsTheConfigurationInForce" /> already strikes for the corpus. It
    ///         is also narrow in practice: the swept fixtures are one construct each, so implementing an
    ///         option drifts that option's own fixture and its immediate neighbours rather than the corpus.
    ///         The failure names them.
    ///     </para>
    ///     <para>
    ///         ⚠ There is deliberately no button that re-stamps these digests without re-running the sweep.
    ///         <c>OracleFixture.Restamp</c> exists for the configuration digest because a configuration can
    ///         provably change without changing a byte of output; a formatter whose output has changed has,
    ///         by construction, changed its output, and there is nothing to certify.
    ///     </para>
    /// </remarks>
    [Fact]
    public void TheCommittedSweep_MeasuredTheFormatterInForce() {
        var json = Path.Combine(
            Corpus.RepositoryRoot,
            "Testing",
            "Rikarin.Skala.Conformance.Sweep",
            "conformance-sweep.json"
        );

        // ⚠ Missing means nobody has measured, which is the one state with nothing to catch out —
        // the same move SweepUnsubstantiated makes, and for the same reason.
        if (!File.Exists(json)) {
            return;
        }

        using var document = JsonDocument.Parse(File.ReadAllText(json));
        var rows = document.RootElement.EnumerateArray().ToArray();
        Assert.True(rows.Length > 0, json + " holds no rows. That is a broken archive, not a clean sweep.");

        var unrecorded = new List<string>();
        var missingFixture = new List<string>();
        var drifted = new List<string>();
        var compared = 0;

        foreach (var row in rows) {
            var key = row.GetProperty("Key").GetString() ?? string.Empty;

            if (!row.TryGetProperty("Values", out var values)
                || values.ValueKind != JsonValueKind.Array
                || !row.TryGetProperty("Fixture", out var recordedFixture)
                || recordedFixture.ValueKind != JsonValueKind.String) {
                unrecorded.Add(key);
                continue;
            }

            var fixture = Path.Combine(
                Corpus.Root,
                (recordedFixture.GetString() ?? string.Empty).Replace('/', Path.DirectorySeparatorChar)
            );
            if (!File.Exists(fixture)) {
                missingFixture.Add(key + " → " + recordedFixture.GetString());
                continue;
            }

            foreach (var value in values.EnumerateArray()) {
                var assigned = value.GetProperty("Value").GetString() ?? string.Empty;
                var recorded = value.GetProperty("SkalaHash").GetString() ?? string.Empty;

                // ⚠ `missing` is the archive's word for "this engine produced nothing here". There is
                // no digest to compare and inventing an agreement is the defect this file exists for.
                if (string.Equals(recorded, "missing", StringComparison.Ordinal)) {
                    continue;
                }

                compared++;
                var now = SkalaSide.Digest(SkalaSide.Format(fixture, key, assigned));
                if (!string.Equals(now, recorded, StringComparison.Ordinal)) {
                    drifted.Add(key + " = " + assigned + ": recorded " + recorded + ", now " + now);
                }
            }
        }

        Assert.True(
            unrecorded.Count == 0,
            Count(unrecorded.Count)
            + " of "
            + Count(rows.Length)
            + " rows in the committed sweep record nothing about Skala's side, so whether the formatter has "
            + "moved since cannot be asked:\n"
            + Sample(unrecorded)
            + "\n\nRe-run `./build.sh Sweep`, which records it. A sweep written before that field existed is "
            + "in exactly the half-measured state this file refuses to tolerate: the tier tests believe its "
            + "verdicts and nothing can say which formatter produced them."
        );

        Assert.True(
            missingFixture.Count == 0,
            Count(missingFixture.Count)
            + " rows name a fixture the corpus no longer has, so their verdicts cannot be re-derived:\n"
            + Sample(missingFixture)
            + "\n\nRe-run `./build.sh Sweep`."
        );

        // ⚠ The population canary. Every assertion above is satisfied by an archive of zero comparable
        // values, and that is the one reading which means the instrument never ran.
        Assert.True(
            compared > 0,
            "the committed sweep records no comparable Skala output at all, so this test asserted nothing."
        );

        Assert.True(
            drifted.Count == 0,
            Count(drifted.Count)
            + " of "
            + Count(compared)
            + " configurations format differently now than when the sweep measured them:\n"
            + Sample(drifted)
            + "\n\nThe sweep's verdicts — and the tiers `OptionCoverageTests` reads off them — describe a "
            + "formatter that no longer exists. Re-run `./build.sh Sweep` in a commit of its own so the "
            + "table moves where it is reviewed."
        );
    }

    /// <summary>
    ///     ⚠ The corpus is the denominator of every sweep number in docs/plan/08, and until this test
    ///     existed nothing asserted how big it is.
    /// </summary>
    /// <remarks>
    ///     ⚠ <b>What went wrong, and what did not.</b> Three table headers in
    ///     <c>docs/plan/08-rule-catalogue.md</c> label the swept tree <c>corpus/real (380 files)</c> while
    ///     <c>Testing/corpus/real</c> holds <b>1 140</b> <c>.cs</c> files, which read as a stale count
    ///     (<see href="https://github.com/Rikarin/SKALA/issues/312" />). It is not one. The corpus keeps
    ///     three copies of every source — <c>X.cs</c>, <c>X.expected.cs</c> and
    ///     <c>X.arranged.expected.cs</c> — so 1 140 = 380 × 3 exactly, and every sweep deliberately staged
    ///     the 380 originals because compiling the twins produces thousands of spurious
    ///     <c>CS0101</c>/<c>CS0111</c>. The headers were under-specified, not wrong. What has no
    ///     instrument either way is the arithmetic itself: a file added to one tree and not to the other
    ///     two moves 380 and 1 140 apart silently, and every table header in the document keeps saying
    ///     380.
    ///     <para>
    ///         So this asserts the shape rather than restating the number in a second place: the swept
    ///         count, the on-disk count, that the second is exactly three times the first, and the
    ///         per-tree split the document names. ⚠ It deliberately does <b>not</b> parse the document's
    ///         headers. A test that rewrote the prose when the corpus moved would let the corpus move
    ///         unreviewed, which is the failure this file exists to reject — the same argument
    ///         <see cref="EveryFixture_RecordsTheConfigurationInForce" /> makes for oracle headers.
    ///     </para>
    /// </remarks>
    [Fact]
    public void TheCorpus_IsTheSizeEveryPublishedSweepMeasured() {
        // The set every sweep stages: `Corpus.Files` already drops the `.expected.cs` twins.
        var swept = Corpus.Files(Corpus.Real);

        // ⚠ Anti-vacuity, in KeyFlipSweep.IsBrokenMeasurement's shape. A missing or renamed directory
        // returns empty from `Corpus.Files`, and every equality below would then be comparing zeros.
        Assert.True(swept.Count > 0, $"{Corpus.SetRoot(Corpus.Real)} enumerated no files; that is not the corpus.");

        var onDisk = Directory
            .EnumerateFiles(Corpus.SetRoot(Corpus.Real), "*.cs", SearchOption.AllDirectories)
            .ToArray();

        Assert.True(
            swept.Count == SweptSources,
            $"docs/plan/08 reports every `corpus/real` sweep over {Count(SweptSources)} staged sources; "
            + $"the tree now stages {Count(swept.Count)}. Every published corpus count in that document "
            + "is a measurement of a tree that no longer exists. Re-derive them or mark the rows, and "
            + "move this constant in the same commit."
        );

        Assert.True(
            onDisk.Length == SweptSources * 3,
            $"`corpus/real` holds {Count(onDisk.Length)} .cs files against {Count(swept.Count)} staged "
            + "sources, and the corpus keeps exactly three copies of each — expected "
            + $"{Count(swept.Count * 3)}. A source is missing one of its `.expected.cs` or "
            + "`.arranged.expected.cs` twins, or a twin has outlived its source. Run `./build.sh Oracle`."
        );

        foreach (var (tree, expected) in Trees) {
            var staged = swept.Count(file => file.RelativePath.StartsWith(tree + "/", StringComparison.Ordinal));
            Assert.True(
                staged == expected,
                $"`corpus/real/{tree}` stages {Count(staged)} sources; docs/plan/08 and issue #312 both "
                + $"record {Count(expected)}. The per-tree split is what says which vendored library a "
                + "sweep's finding came from, so a moved boundary re-scopes every number attributed to it."
            );
        }
    }

    static OracleHeader? HeaderOf(string path) {
        using var reader = new StreamReader(path);
        return reader.ReadLine() is { } line ? OracleHeader.Parse(line) : null;
    }

    static string Relative(string path) => Path.GetRelativePath(Corpus.Root, path).Replace('\\', '/');

    static string Sample(IEnumerable<string> lines) {
        var listed = lines.Take(Examples + 1).ToArray();
        return string.Join("\n", listed.Take(Examples).Select(static line => "  " + line))
            + (listed.Length > Examples ? "\n  …" : string.Empty);
    }

    static string Count(int value) => value.ToString(CultureInfo.InvariantCulture);
}
