using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;
using Rikarin.Skala.Rules.Metadata;
using System;
using System.Collections.Immutable;

namespace Rikarin.Skala.Rules.Design;

/// <summary><c>SK6030</c> — a type declared with no namespace around it at all.</summary>
/// <remarks>
///     The global namespace is one flat name table shared by every assembly a compilation references,
///     and it is the one namespace a <c>using</c> cannot name. A type in it collides with every other
///     global type of the same name in the closure, and the collision surfaces in a consumer's build
///     rather than in this one.
///     <para>
///         ⚠ Purely syntactic, and deliberately so: "which namespace is this declaration in" is answered
///         by the declaration's parent node. The rule therefore runs under <c>--load=loose</c>, which
///         matters because a repository with no project files is exactly where a stray global type is
///         most likely to have been generated by an agent.
///     </para>
/// </remarks>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class GlobalNamespaceTypeAnalyzer : DiagnosticAnalyzer {
    static readonly DiagnosticDescriptor Descriptor = SkalaRule.Descriptor(RuleIds.TypeInGlobalNamespace);

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(Descriptor);

    public override void Initialize(AnalysisContext context) {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        // Every kind a compilation unit can hold directly. `enum` and `delegate` are in: they occupy
        // the same name table as a class and collide the same way.
        context.RegisterSyntaxNodeAction(
            Analyze,
            SyntaxKind.ClassDeclaration,
            SyntaxKind.StructDeclaration,
            SyntaxKind.RecordDeclaration,
            SyntaxKind.RecordStructDeclaration,
            SyntaxKind.InterfaceDeclaration,
            SyntaxKind.EnumDeclaration,
            SyntaxKind.DelegateDeclaration
        );
    }

    static void Analyze(SyntaxNodeAnalysisContext context) {
        var declaration = (MemberDeclarationSyntax)context.Node;

        // ⚠ The parent decides it, and only the *direct* parent. A declaration inside a namespace has a
        // namespace node above it; a nested type has a type node above it and takes its container's
        // namespace, so reporting one would report the outer type's mistake a second time.
        if (declaration.Parent is not CompilationUnitSyntax) {
            return;
        }

        var identifier = Identifier(declaration);
        if (identifier.IsKind(SyntaxKind.None)) {
            return;
        }

        foreach (var modifier in declaration.Modifiers) {
            // A `file` type is visible only inside the file that declares it, so it is in the global
            // namespace and in nobody's way — which is what the modifier is for. It is the one shape
            // where "no namespace" is the correct answer rather than an omission.
            if (modifier.IsKind(SyntaxKind.FileKeyword)) {
                return;
            }
        }

        // ⚠ `Program` is exempt, and it is not a courtesy. A file with top-level statements gets a
        // compiler-generated `Program` in the global namespace, and `public partial class Program { }`
        // — the documented way to make it visible to `WebApplicationFactory<Program>` — has to be in
        // the global namespace too, or it declares a different type and the test host cannot find the
        // entry point. There is no namespace this declaration could be moved to.
        if (string.Equals(identifier.ValueText, "Program", StringComparison.Ordinal)) {
            return;
        }

        context.ReportDiagnostic(
            Diagnostic.Create(
                Descriptor,
                identifier.GetLocation(),
                "`"
                + identifier.ValueText
                + "` is declared in the global namespace, where it shares one flat name table with "
                + "every referencing assembly and no `using` can disambiguate it; give it a namespace"
            )
        );
    }

    static SyntaxToken Identifier(MemberDeclarationSyntax declaration) =>
        declaration switch {
            BaseTypeDeclarationSyntax type => type.Identifier,
            DelegateDeclarationSyntax delegateDeclaration => delegateDeclaration.Identifier,
            _ => default
        };
}
