// <auto-generated/>
// Generated code is excluded: what a generator emits is not a shape anybody chose to write.
namespace Fixtures;

class GeneratedPicker {
    public static string Pick(bool a, bool b, bool c) => a ? b ? c ? "abc" : "ab" : "a" : "none";
}
