// <auto-generated/>
// analyzer-option: dotnet_code_quality.SK7083.threshold = 1
// Generated code is excluded: a generator writing the same key five times is not a rename anybody
// will have to do by hand.
namespace Fixtures;

class GeneratedKeys {
    public static readonly string A = "tenant-id";

    public static readonly string B = "tenant-id";

    public static readonly string C = "tenant-id";

    public static readonly string D = "tenant-id";
}
