<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rikarin.Skala.Rules.Generator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../../Core/Rikarin.Skala.Options.Generator/Json.cs" Link="Json.cs" />
    <Compile Include="../../Core/Rikarin.Skala.Options.Generator/Compat.cs" Link="Compat.cs" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
    <AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
  </ItemGroup>
</Project>
