using Microsoft.CodeAnalysis;
using Rikarin.Skala.Options.Generator;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;

namespace Rikarin.Skala.Rules.Generator;

/// <summary>
///     Reads <c>rules.json</c> and emits the rule catalogue: <c>RuleIds</c>, <c>RuleInfo</c> and the
///     <c>RuleCatalog</c> lookup the analyzers, the docs generator, <c>skala explain</c> and the SARIF
///     <c>rules[]</c> block all read.
/// </summary>
/// <remarks>
///     docs/plan/08-rule-catalogue.md § "Rule metadata": one source, four surfaces.
///     <para>
///         ⚠ It is a source generator rather than a runtime JSON read for the same reason the option
///         registry is: <c>Rikarin.Skala.Rules</c> is <c>netstandard2.0</c> and loads into <c>csc</c> and
///         into Rider, so a <c>System.Text.Json</c> in its dependency closure is a way for the analyzer
///         load to fail with an error message that names none of it (docs/plan/02 § "The project graph").
///         The JSON reader is the one the option generator already carries, linked rather than copied.
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class RulesGenerator : IIncrementalGenerator {
    const string FileName = "rules.json";
    const string Namespace = "Rikarin.Skala.Rules.Metadata";

    static readonly DiagnosticDescriptor MissingCatalogue = new(
        "SKR001",
        "The rule catalogue is missing",
        "No AdditionalFile named '{0}' was found; the rule catalogue cannot be generated",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    static readonly DiagnosticDescriptor UnreadableCatalogue = new(
        "SKR002",
        "The rule catalogue could not be read",
        "'{0}' could not be read: {1}",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    static readonly DiagnosticDescriptor MalformedId = new(
        "SKR003",
        "A rule id is not in the SK#### shape",
        """'{0}' is not a rule id; ids are 'SK' followed by four digits (docs/plan/02 § "Naming")""",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    static readonly DiagnosticDescriptor DuplicateId = new(
        "SKR004",
        "A rule id is allocated twice",
        "'{0}' appears more than once in the catalogue; ADR-012 makes an id permanent and therefore unique",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var catalogue = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(FileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (text, token) => (text.Path, Content: text.GetText(token)?.ToString()))
            .Collect();

        context.RegisterSourceOutput(catalogue, static (production, files) => Emit(production, files));
    }

    static void Emit(SourceProductionContext production, ImmutableArray<(string Path, string? Content)> files) {
        if (files.Length == 0) {
            production.ReportDiagnostic(Diagnostic.Create(MissingCatalogue, Location.None, FileName));
            return;
        }

        var (path, content) = files[0];
        if (content is null) {
            production.ReportDiagnostic(Diagnostic.Create(UnreadableCatalogue, Location.None, path, "no text"));
            return;
        }

        List<RuleModel> rules;
        try {
            rules = RuleModel.ReadAll(Json.Parse(content));
        } catch (JsonException exception) {
            production.ReportDiagnostic(Diagnostic.Create(UnreadableCatalogue, Location.None, path, exception.Message));
            return;
        }

        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var rule in rules) {
            if (!RuleIdSyntax.IsRuleId(rule.Id)) {
                production.ReportDiagnostic(Diagnostic.Create(MalformedId, Location.None, rule.Id));
            }

            if (!seen.Add(rule.Id)) {
                production.ReportDiagnostic(Diagnostic.Create(DuplicateId, Location.None, rule.Id));
            }
        }

        production.AddSource("RuleCatalog.g.cs", EmitCatalog(rules));
    }

    static string EmitCatalog(List<RuleModel> rules) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> Generated from rules.json by Rikarin.Skala.Rules.Generator.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.Append("namespace ").Append(Namespace).AppendLine(";");
        builder.AppendLine();

        builder.AppendLine("/// <summary>Every rule id, as constants, so a typo is a compile error.</summary>");
        builder.AppendLine("public static class RuleIds {");
        foreach (var rule in rules) {
            builder.Append("    /// <summary>").Append(Escape(rule.Title)).AppendLine("</summary>");
            builder.Append("    public const string ")
                .Append(Identifier(rule.Concept))
                .Append(" = \"")
                .Append(rule.Id)
                .AppendLine("\";");
        }

        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine(
            "/// <summary>The catalogue, in id order. The single source for every rule surface.</summary>"
        );
        builder.AppendLine("public static class RuleCatalog {");
        builder.AppendLine("    public static IReadOnlyList<RuleInfo> All { get; } = new RuleInfo[] {");
        foreach (var rule in rules.OrderBy(static r => r.Id, StringComparer.Ordinal)) {
            builder.AppendLine("        new(");
            builder.Append("            Id: \"").Append(rule.Id).AppendLine("\",");
            builder.Append("            Concept: \"").Append(rule.Concept).AppendLine("\",");
            builder.Append("            Title: ").Append(Literal(rule.Title)).AppendLine(",");
            builder.Append("            Category: \"").Append(rule.Category).AppendLine("\",");
            builder.Append("            DefaultSeverity: RuleSeverity.")
                .Append(Severity(rule.DefaultSeverity))
                .AppendLine(",");
            builder.Append("            Scope: RuleScope.").Append(rule.Scope).AppendLine(",");
            builder.Append("            RequiresSemantics: ")
                .Append(rule.RequiresSemantics ? "true" : "false")
                .AppendLine(",");
            builder.Append("            HasFix: ").Append(rule.HasFix ? "true" : "false").AppendLine(",");
            builder.Append("            FixIsSafe: ").Append(rule.FixIsSafe ? "true" : "false").AppendLine(",");
            builder.Append("            Retired: ").Append(rule.Retired ? "true" : "false").AppendLine(",");
            builder.Append("            Supersedes: ").Append(StringArray(rule.Supersedes)).AppendLine(",");
            builder.Append("            Since: \"").Append(rule.Since).AppendLine("\",");
            builder.Append("            LanguageVersion: ")
                .Append(rule.LanguageVersion is null ? "null" : Literal(rule.LanguageVersion))
                .AppendLine(",");
            builder.Append("            Summary: ").Append(Literal(rule.Summary)).AppendLine(",");
            builder.Append("            Rationale: ").Append(Literal(rule.Rationale)).AppendLine(",");
            builder.Append("            BadExample: ").Append(Literal(rule.BadExample)).AppendLine(",");
            builder.Append("            GoodExample: ").Append(Literal(rule.GoodExample)).AppendLine(",");
            builder.Append("            FalsePositives: ").Append(Literal(rule.FalsePositives)).AppendLine(",");
            builder.Append("            Configuration: ").AppendLine(StringArray(rule.Configuration));
            builder.AppendLine("        ),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
        builder.AppendLine("    static readonly Dictionary<string, RuleInfo> ById =");
        builder.AppendLine("        BuildIndex();");
        builder.AppendLine();
        builder.AppendLine("    static Dictionary<string, RuleInfo> BuildIndex() {");
        builder.AppendLine("        var index = new Dictionary<string, RuleInfo>(StringComparer.OrdinalIgnoreCase);");
        builder.AppendLine("        foreach (var rule in All) {");
        builder.AppendLine("            index[rule.Id] = rule;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return index;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine(
            "    /// <summary>The rule with this id, or null. ⚠ Case-insensitive: `sk1010` is what people type.</summary>"
        );
        builder.AppendLine("    public static RuleInfo? Find(string id) =>");
        builder.AppendLine("        id != null && ById.TryGetValue(id, out var rule) ? rule : null;");
        builder.AppendLine();
        builder.AppendLine("    public static RuleInfo Get(string id) =>");
        builder.AppendLine(
            """        Find(id) ?? throw new KeyNotFoundException($"'{id}' is not a Skala rule id.");"""
        );
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>⚠ `new[] { }` does not infer an element type; an empty list has to be spelled out.</summary>
    static string StringArray(List<string> values) =>
        values.Count == 0
            ? "System.Array.Empty<string>()"
            : "new[] { " + string.Join(", ", values.Select(Literal)) + " }";

    static string Severity(string value) =>
        value switch {
            "error" => "Error",
            "warning" => "Warning",
            "suggestion" => "Suggestion",
            "hint" => "Hint",
            "none" => "None",
            _ => "Suggestion"
        };

    /// <summary>
    ///     A stable C# identifier for a rule's concept slug: <c>is-null-pattern</c> → <c>IsNullPattern</c>.
    /// </summary>
    static string Identifier(string concept) {
        var builder = new StringBuilder(concept.Length);
        var upper = true;
        foreach (var c in concept) {
            if (c == '-' || c == '_' || c == '.') {
                upper = true;
                continue;
            }

            builder.Append(upper ? char.ToUpperInvariant(c) : c);
            upper = false;
        }

        return builder.ToString();
    }

    static string Escape(string value) => value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    static string Literal(string value) {
        var builder = new StringBuilder(value.Length + 8);
        builder.Append('"');
        foreach (var c in value) {
            switch (c) {
                case '"':
                    builder.Append("\\\"");
                    break;

                case '\\':
                    builder.Append("""\\""");
                    break;

                case '\n':
                    builder.Append("""\n""");
                    break;

                case '\r':
                    builder.Append("""\r""");
                    break;

                case '\t':
                    builder.Append("""\t""");
                    break;

                default:
                    if (c < ' ') {
                        builder.Append("""\u""").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    } else {
                        builder.Append(c);
                    }

                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }
}

/// <summary>One <c>rules.json</c> entry, as the generator reads it.</summary>
internal sealed class RuleModel {
    public string Id { get; private set; } = string.Empty;
    public string Concept { get; private set; } = string.Empty;
    public string Title { get; private set; } = string.Empty;
    public string Category { get; private set; } = string.Empty;
    public string DefaultSeverity { get; private set; } = "suggestion";
    public string Scope { get; private set; } = "Syntax";
    public bool RequiresSemantics { get; private set; }
    public bool HasFix { get; private set; }
    public bool FixIsSafe { get; private set; }
    public bool Retired { get; private set; }
    public List<string> Supersedes { get; } = new();
    public string Since { get; private set; } = "0.6";
    public string? LanguageVersion { get; private set; }
    public string Summary { get; private set; } = string.Empty;
    public string Rationale { get; private set; } = string.Empty;
    public string BadExample { get; private set; } = string.Empty;
    public string GoodExample { get; private set; } = string.Empty;
    public string FalsePositives { get; private set; } = string.Empty;
    public List<string> Configuration { get; } = new();

    public static List<RuleModel> ReadAll(JsonValue root) {
        var result = new List<RuleModel>();
        foreach (var entry in root["rules"].Items) {
            result.Add(Read(entry));
        }

        return result;
    }

    static RuleModel Read(JsonValue entry) {
        var rule = new RuleModel {
            Id = String(entry, "id"),
            Concept = String(entry, "concept"),
            Title = String(entry, "title"),
            Category = String(entry, "category"),
            DefaultSeverity = String(entry, "defaultSeverity", "suggestion"),
            Scope = String(entry, "scope", "Syntax"),
            RequiresSemantics = entry["requiresSemantics"].AsBool(),
            HasFix = entry["hasFix"].AsBool(),
            FixIsSafe = entry["fixIsSafe"].AsBool(),
            Retired = entry["retired"].AsBool(),
            Since = String(entry, "since", "0.6"),
            LanguageVersion = entry["languageVersion"].AsString(),
            Summary = String(entry, "summary"),
            Rationale = String(entry, "rationale"),
            FalsePositives = String(entry, "falsePositives")
        };

        rule.BadExample = String(entry["examples"], "bad");
        rule.GoodExample = String(entry["examples"], "good");
        rule.Supersedes.AddRange(entry["supersedes"].AsStringList());
        rule.Configuration.AddRange(entry["configuration"].AsStringList());
        return rule;
    }

    static string String(JsonValue owner, string name, string fallback = "") => owner[name].AsString() ?? fallback;
}
