using Microsoft.CodeAnalysis;
using Rikarin.Skala.Options.Generator;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Rikarin.Skala.Rules.Generator;

/// <summary>
///     Reads <c>taint.json</c> and emits <c>TaintTable</c> — the sources, propagators, sanitizers and
///     sinks the <c>SK5001</c>/<c>SK5002</c> analyzers match symbols against.
/// </summary>
/// <remarks>
///     docs/plan/08-rule-catalogue.md § "SK5000 — Security" asks for "a declared source/sink/sanitizer
///     table in <c>taint.json</c>" and the word that matters is <em>declared</em>: adding a sink for a
///     database client Skala has never heard of has to be an edit to a data file, not a change to an
///     analyzer, or the table is not a table.
///     <para>
///         ⚠ A generator rather than a runtime JSON read, for the reason
///         <see cref="RulesGenerator" /> already gives: <c>Rikarin.Skala.Rules</c> is
///         <c>netstandard2.0</c> and loads into <c>csc</c> and into Rider, so a <c>System.Text.Json</c> in
///         its dependency closure is an analyzer-load failure whose message names none of it
///         (docs/plan/02 § "The project graph").
///     </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class TaintGenerator : IIncrementalGenerator {
    const string FileName = "taint.json";
    const string Namespace = "Rikarin.Skala.Rules.Metadata";

    static readonly DiagnosticDescriptor MissingTable = new(
        "SKR010",
        "The taint table is missing",
        "No AdditionalFile named '{0}' was found; the taint table cannot be generated",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    static readonly DiagnosticDescriptor UnreadableTable = new(
        "SKR011",
        "The taint table could not be read",
        "'{0}' could not be read: {1}",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    /// <summary>
    ///     ⚠ A sink whose <c>rule</c> is not an id is a sink nothing reports, and it would look like a
    ///     working entry.
    /// </summary>
    static readonly DiagnosticDescriptor MalformedSink = new(
        "SKR012",
        "A taint sink does not name a rule id",
        "The sink on '{0}.{1}' declares rule '{2}', which is not in the SK#### shape",
        "Skala.Rules",
        DiagnosticSeverity.Error,
        true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context) {
        var table = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(FileName, StringComparison.OrdinalIgnoreCase))
            .Select(static (text, token) => (text.Path, Content: text.GetText(token)?.ToString()))
            .Collect();

        context.RegisterSourceOutput(table, static (production, files) => Emit(production, files));
    }

    static void Emit(SourceProductionContext production, ImmutableArray<(string Path, string? Content)> files) {
        if (files.Length == 0) {
            production.ReportDiagnostic(Diagnostic.Create(MissingTable, Location.None, FileName));
            return;
        }

        var (path, content) = files[0];
        if (content is null) {
            production.ReportDiagnostic(Diagnostic.Create(UnreadableTable, Location.None, path, "no text"));
            return;
        }

        TaintModel model;
        try {
            model = TaintModel.Read(Json.Parse(content));
        } catch (JsonException exception) {
            production.ReportDiagnostic(Diagnostic.Create(UnreadableTable, Location.None, path, exception.Message));
            return;
        }

        foreach (var sink in model.Sinks) {
            if (!RuleIdSyntax.IsRuleId(sink.Rule)) {
                production.ReportDiagnostic(
                    Diagnostic.Create(MalformedSink, Location.None, sink.Type, sink.Member, sink.Rule)
                );
            }
        }

        production.AddSource("TaintTable.g.cs", Render(model));
    }

    static string Render(TaintModel model) {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> Generated from taint.json by Rikarin.Skala.Rules.Generator.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine();
        builder.Append("namespace ").Append(Namespace).AppendLine(";");
        builder.AppendLine();

        builder.AppendLine(
            "/// <summary>One declared member: a type name and the members on it that matter.</summary>"
        );
        builder.AppendLine("public sealed record TaintMembers(string Type, IReadOnlyList<string> Members);");
        builder.AppendLine();

        builder.AppendLine("/// <summary>One declared sink, and what a reader should do instead.</summary>");
        builder.AppendLine("public sealed record TaintSink(");
        builder.AppendLine("    string Rule,");
        builder.AppendLine("    string Type,");
        builder.AppendLine("    string Member,");
        builder.AppendLine("    string Kind,");
        builder.AppendLine("    IReadOnlyList<string> Parameters,");
        builder.AppendLine("    string What,");
        builder.AppendLine("    string Instead) {");
        builder.AppendLine("    /// <summary>Whether the entry matches every member of its type.</summary>");
        builder.AppendLine("    public bool MatchesAnyMember => Member == \"*\";");
        builder.AppendLine("}");
        builder.AppendLine();

        builder.AppendLine(
            "/// <summary>The taint table, as taint.json declares it. See docs/plan/08 § \"SK5000 — Security\".</summary>"
        );
        builder.AppendLine("public static class TaintTable {");

        EmitMembers(builder, "Sources", model.Sources);
        EmitMembers(builder, "Propagators", model.Propagators);
        EmitMembers(builder, "Sanitizers", model.Sanitizers);

        builder.AppendLine("    /// <summary>Where a tainted value must never arrive, per rule.</summary>");
        builder.AppendLine("    public static IReadOnlyList<TaintSink> Sinks { get; } = new TaintSink[] {");
        foreach (var sink in model.Sinks) {
            builder.Append("        new(")
                .Append(Literal(sink.Rule))
                .Append(", ")
                .Append(Literal(sink.Type))
                .Append(", ")
                .Append(Literal(sink.Member))
                .Append(", ")
                .Append(Literal(sink.Kind))
                .Append(", ")
                .Append(StringArray(sink.Parameters))
                .Append(", ")
                .Append(Literal(sink.What))
                .Append(", ")
                .Append(Literal(sink.Instead))
                .AppendLine("),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();

        builder.AppendLine(
            "    /// <summary>Every type named anywhere in the table, for the compilation-start gate.</summary>"
        );
        builder.AppendLine("    /// <remarks>");
        builder.AppendLine(
            "    /// ⚠ The gate is what keeps the taint engine off the warm path. A compilation in which"
        );
        builder.AppendLine(
            "    /// not one source type resolves cannot produce a tainted value, so the analyzer registers"
        );
        builder.AppendLine(
            "    /// nothing at all rather than building a control-flow graph to discover the same thing."
        );
        builder.AppendLine("    /// </remarks>");
        builder.AppendLine("    public static IReadOnlyList<string> SourceTypes { get; } = new string[] {");
        foreach (var source in model.Sources) {
            builder.Append("        ").Append(Literal(source.Type)).AppendLine(",");
        }

        builder.AppendLine("    };");
        builder.AppendLine("}");

        return builder.ToString();
    }

    static void EmitMembers(StringBuilder builder, string name, List<TaintMemberModel> entries) {
        builder.Append("    /// <summary>The declared ").Append(name.ToLowerInvariant()).AppendLine(".</summary>");
        builder.Append("    public static IReadOnlyList<TaintMembers> ")
            .Append(name)
            .AppendLine(" { get; } = new TaintMembers[] {");
        foreach (var entry in entries) {
            builder.Append("        new(")
                .Append(Literal(entry.Type))
                .Append(", ")
                .Append(StringArray(entry.Members))
                .AppendLine("),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
    }

    static string StringArray(IReadOnlyList<string> values) =>
        values.Count == 0
            ? "Array.Empty<string>()"
            : "new string[] { " + string.Join(", ", values.Select(Literal)) + " }";

    static string Literal(string value) {
        var builder = new StringBuilder(value.Length + 2);
        builder.Append('"');
        foreach (var c in value) {
            switch (c) {
                case '"':
                    builder.Append("\\\"");
                    break;
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '\n':
                    builder.Append("\\n");
                    break;
                case '\r':
                    builder.Append("\\r");
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        builder.Append('"');
        return builder.ToString();
    }
}

/// <summary>One <c>type</c> plus <c>members</c> entry from <c>taint.json</c>.</summary>
internal sealed class TaintMemberModel {
    public string Type { get; set; } = string.Empty;

    public List<string> Members { get; } = new();
}

/// <summary>One <c>sinks</c> entry from <c>taint.json</c>.</summary>
internal sealed class TaintSinkModel {
    public string Rule { get; set; } = string.Empty;

    public string Type { get; set; } = string.Empty;

    public string Member { get; set; } = string.Empty;

    public string Kind { get; set; } = "method";

    public List<string> Parameters { get; } = new();

    public string What { get; set; } = string.Empty;

    public string Instead { get; set; } = string.Empty;
}

/// <summary><c>taint.json</c> as the generator reads it.</summary>
internal sealed class TaintModel {
    public List<TaintMemberModel> Sources { get; } = new();

    public List<TaintMemberModel> Propagators { get; } = new();

    public List<TaintMemberModel> Sanitizers { get; } = new();

    public List<TaintSinkModel> Sinks { get; } = new();

    public static TaintModel Read(JsonValue root) {
        var model = new TaintModel();
        ReadMembers(root["sources"], model.Sources);
        ReadMembers(root["propagators"], model.Propagators);
        ReadMembers(root["sanitizers"], model.Sanitizers);

        foreach (var entry in root["sinks"].Items) {
            var sink = new TaintSinkModel {
                Rule = entry["rule"].AsString() ?? string.Empty,
                Type = entry["type"].AsString() ?? string.Empty,
                Member = entry["member"].AsString() ?? string.Empty,
                Kind = entry["kind"].AsString() ?? "method",
                What = entry["what"].AsString() ?? string.Empty,
                Instead = entry["instead"].AsString() ?? string.Empty
            };

            sink.Parameters.AddRange(entry["parameters"].AsStringList());
            model.Sinks.Add(sink);
        }

        return model;
    }

    static void ReadMembers(JsonValue array, List<TaintMemberModel> into) {
        foreach (var entry in array.Items) {
            var member = new TaintMemberModel { Type = entry["type"].AsString() ?? string.Empty };
            member.Members.AddRange(entry["members"].AsStringList());
            into.Add(member);
        }
    }
}
