<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rikarin.Skala.Rules.Metadata</RootNamespace>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Rikarin.Skala.Rules.Generator/Rikarin.Skala.Rules.Generator.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="rules.json" />
    <EmbeddedResource Include="rules.json" LogicalName="Rikarin.Skala.Rules.Metadata.rules.json" />
    <AdditionalFiles Include="taint.json" />
    <EmbeddedResource Include="taint.json" LogicalName="Rikarin.Skala.Rules.Metadata.taint.json" />
  </ItemGroup>
</Project>
