// <auto-generated/>
// A generator writes the member name out because it has one and the substitution would give it
// the same string; it is not a decision made here.
using System.Runtime.CompilerServices;

namespace Fixtures {
    sealed class GeneratedTracer {
        public void Run() {
            Trace("started", nameof(Run));
        }

        static void Trace(string message, [CallerMemberName] string? member = null) { }
    }
}
