// <auto-generated/>
// A generator emits the construction its template holds; it is not a decision made here.
using System.Collections.Immutable;

namespace Fixtures {
    sealed class GeneratedIds {
        public static ImmutableArray<int> All() => new ImmutableArray<int> { 1, 2 };
    }
}
