<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rikarin.Skala.Reporting</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sarif.Sdk" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Core/Rikarin.Skala.Core/Rikarin.Skala.Core.csproj" />
    <ProjectReference Include="../../Rules/Rikarin.Skala.Rules.Metadata/Rikarin.Skala.Rules.Metadata.csproj" />
  </ItemGroup>
</Project>
