// <auto-generated/>
// A generator emits both overloads from one template; it is not a decision made here.
namespace Fixtures {
    internal sealed class GeneratedRenderer {
        internal string Render(string text) => Render(text, 4);

        internal string Render(string text, int indent) => new string(' ', indent) + text;
    }
}
