// <auto-generated/>
// A generator emits the parameter modifier its template holds; it is not a decision made here.
namespace Fixtures {
    struct GeneratedCounter {
        public int Value;

        public void Increment() => Value++;
    }

    sealed class GeneratedRunner {
        public static void Bump(in GeneratedCounter counter) => counter.Increment();
    }
}
