// <auto-generated/>
// A generator emits the comparison its template holds; it is not a decision made here.
using System;

namespace Fixtures {
    sealed class GeneratedReader {
        public static bool Same(ReadOnlySpan<char> left, ReadOnlySpan<char> right) => left == right;
    }
}
