// <auto-generated/>
// A generator emits the signature its template holds; it is not a decision made here.
using System.Threading.Tasks;

public sealed class GeneratedPoller {
    public async Task PollAsync() {
        await Task.Delay(50);
    }
}
